### ISSUE TITLE
Sending metrics to mimir does not seem to isolate environments

### ISSUE THREAD

**Issue by danhawkins** [encoredev/encore#1051]
I've setup a "grafana cloud" metrics endpoint using memir, we started to ship production metrics, everything is working fine. In the metrics view of encore, we see a point in time where metrics stop and new metrics start. 

When I try to connect staging to the same metrics target, and deploy. I immediately see metrics, which appear to be my production metrics, so it seems like the metrics view of encore is no correctly using env tags.

This is the view of staging while it was still using encore for metrics

![Screenshot 2024-02-28 at 10 49 18](https://github.com/encoredev/encore/assets/108635/0d3d1298-21ab-42d4-b2cb-709490a35701)

and this is the view immediatly after switching to the mimir target (there should be no metrics there)

![Screenshot 2024-02-28 at 10 50 34](https://github.com/encoredev/encore/assets/108635/8b283afe-901e-4ff3-8942-b70641854789)

**Comment by eandre** [comment]
Thanks @danhawkins. Deploying a fix as we speak.
