### ISSUE TITLE
Clarify Time Zone for Cron Expressions in Documentation

### ISSUE THREAD

**Issue by tomassarmiento** [encoredev/encore#1059]
The documentation for Encore's Cron Jobs mentions scheduling operates based on Coordinated Universal Time (UTC) in parentheses. However, this information is not clearly emphasized and could be easily overlooked by new users.

So I would update the documentation to include a clear statement indicating that all scheduling in Encore's Cron Jobs is based on UTC time. For example, add a brief note such as "Note: All scheduling in Encore's Cron Jobs operates in Coordinated Universal Time (UTC)." This addition will help users accurately schedule their tasks without misunderstanding the time zone.

Does this align with the project, or is it too small of an issue?

Thanks

**Comment by eandre** [comment]
Hi @tomassarmiento, if you have specific suggestions on how to improve the docs, please create a PR! The cron jobs docs page is here: https://github.com/encoredev/encore/blob/main/docs/primitives/cron-jobs.md
