### ISSUE TITLE
`Set-Cookie` can only send one `Set-Cookie` header response

### ISSUE THREAD

**Issue by tuckers-tech** [encoredev/encore#1094]
Hey Encore Team!  

I ran into another bug with the `Set-Cookie` headers.  If we need to set two separate cookies on login, the [`Set-Cookie` docs say](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie):

> To send multiple cookies, multiple Set-Cookie headers should be sent in the same response.

I tried doing the following:
```
export interface AuthResponse {
  accessCookie: Header<'Set-Cookie'> //(sets cookie access_token)
  refreshCookie: Header<'Set-Cookie'> //(sets cookie refresh_token)
}
```

Only the `refresh_token` cookie will be set in this case.  If this is supported in another form I'm happy to implement it in a different way!

**Comment by eandre** [comment]
Thanks for the report! Encore v1.34.4-beta.5 is out now which fixes this!
