### ISSUE TITLE
Generated client has type error when using optional `AuthParams`

### ISSUE THREAD

**Issue by tuckers-tech** [encoredev/encore#1131]
I have a system that authenticates via secure cookie _or_ api token (depending on if the client is the browser or CLI).  I currently have this set up on the encore side with:
```ts
interface AuthParams {
  cookie?: Header<'Cookie'>
  token?: Header<'x-api-token'>
}
```

This works great on the backend side, I didn't run into any issues until I started integrating the client.  I can generate the client but when I try and build (exec TS check) I'm running into an issue with the following generated lines in the `callAPI` method
```ts
if (authData) {
  init.headers['cookie'] = authData.cookie
  init.headers['x-api-token'] = authData.token
}
```

This throws the following error because both `authData.cookie` and `authData.token` are optional
```ts
Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.
```

**Comment by eandre** [comment]
This is being fixed in #1411, thanks!
