### ISSUE TITLE
TypeScript Client improvements

### ISSUE THREAD

**Issue by ValeriaVG** [encoredev/encore#114]
Client generation functionality is awesome, but I think there are some things that would make it better:

1. Add the ability to change token without re-creating a client instance. A simple solution would be to expose setter/getter for the said token instead of providing token as a constructor argument
2. Check that token is truthy before adding auth header. I've accidentally set it to `null` and requests to not-auth paths started to fail with 401
3. Return error response as parsed json instead of a stringified error. One solution could be to override the fetch implementation altogether, e.g. by providing it as one of the constructor options

Let me know what makes sense and I can implement it.

**Comment by eandre** [comment]
All of these ideas make a lot of sense and we'd be happy to incorporate all of them! There's also #50 with another set of improvements that we should add. Perhaps it's time to create a proper npm package to hold things like the error type you described and so on?

**Comment by ValeriaVG** [comment]
Given that the common types are quite small I'm not sure if it's worth enforcing a separate dependency. 
I'd imagine that a clean zero-dependency TypeScript would work without problems for node, deno and browsers (through a bundler).

I'd remove BaseClient completely and instead would pass Client's `exec` or `call` method to the service clients. This way the behaviour can be customized for almost any scenario by simple extending the Client class if needed and providing decent defaults otherwise.
 
 What do you think?

**Comment by eandre** [comment]
That's true, I agree with you. If you have a vision for how you think this should look, go for that! I trust your judgement :)
