### ISSUE TITLE
`-c`/`--create` flag for `encore ns switch` fails if namespace already exists

### ISSUE THREAD

**Issue by melkstam** [encoredev/encore#1226]
When using the `-c`/`--create` flag for `encore ns switch`, I expect it to create if not already exists. However, it currently fails if the namespace already exists. 

![example](https://github.com/encoredev/encore/assets/10176195/92885a50-fac5-444e-9731-fe5c9ab12e22)

**Comment by eandre** [comment]
The error message can certainly be better, but it seems correct to me that you get an error. `git switch -c` has the same behavior:

```bash
$ git branch test
$ git switch -c test
fatal: a branch named 'test' already exists
```

**Comment by melkstam** [comment]
Is there any difference between `encore ns create` and `encore ns switch -c` then? I expected this to be the difference
