### ISSUE TITLE
Due to some reasons, I need to engage in self-hosting services.

### ISSUE THREAD

**Issue by call-81192** [encoredev/encore#1290]
1.  The information provided in the official documentation is insufficient, and I don't know how to configure some aspects of self-hosting.

2.  I need to run which Docker containers myself to support the project.

3.  Can you provide a minimal example?

**Comment by call-81192** [comment]
I using golang

**Comment by ImBIOS** [comment]
This is a question I think, not an issue (feature req/bug)

here's the answer maybe: https://encore.dev/docs/how-to/self-host

**Comment by seivan** [comment]
> This is a question I think, not an issue (feature req/bug)
> 
> here's the answer maybe: https://encore.dev/docs/how-to/self-host

Yeah but it doesn't tell you how things work and what requirements there are. Afaik Encore needs a ton of services from e.g AWS and you need to manage access via secrets and urls but also make sure you got permissions for their usage.

**Comment by marcuskohlberg** [comment]
Hi, we've now improved the self-host tooling and added more documentation.
- You can find the docs for using the new `encore build` command here: https://encore.dev/docs/self-host/docker-build
- Here are the docs for configuration: https://encore.dev/docs/self-host/configure-infra
- Here's a tutorial for deploying to DigitalOcean as an example: https://encore.dev/docs/self-host/deploy-digitalocean

If you have questions, join Discord and we'll help you out: https://encore.dev/discord
