### ISSUE TITLE
encore run using proxy

### ISSUE THREAD

**Issue by Rubyer77** [encoredev/encore#1294]
Are proxy envvars honored when using `encore run` ?
I try
```
(export {PROXY_URI,HTTPS_PROXY,HTTP_PROXY,https_proxy,http_proxy}=http://127.0.0.1:8888; encore run)
```
and it does not seem to use the proxy I provide

`http://127.0.0.1:8888` is a standalone http proxy I run on my local machine

**Comment by eandre** [comment]
This should be respected in the same way as Go normally respects these variables. Encore doesn't modify the behavior of `net/http`. Did you resolve the issue you were having?
