### ISSUE TITLE
tsparser: Cargo.lock file appears to be outdated

### ISSUE THREAD

**Issue by luisnquin** [encoredev/encore#1295]
I'm working on packaging everything for [nixpkgs](https://github.com/NixOS/nixpkgs), but I'm encountering errors due to inconsistencies between the version (and checksum) of the **tracing** crate in the [Cargo.lock](https://github.com/encoredev/encore/blob/506a5ce835e4fd7796745bf8667d317965a2ea6e/tsparser/Cargo.lock#L1596) and [Cargo.toml](https://github.com/encoredev/encore/blob/506a5ce835e4fd7796745bf8667d317965a2ea6e/tsparser/Cargo.toml#L49) files. I'm currently implementing workarounds to resolve this issue.

Here's the [issue](https://github.com/NixOS/nixpkgs/issues/327520) and [pull request](https://github.com/NixOS/nixpkgs/pull/328519) where we are trying to package this project in nix.

Thanks for your reading :)

**Comment by fredr** [comment]
Nice one, and thanks for opening this issue. 

We use cargo workspaces, so all rust projects in the repo use the same cargo.lock file in the root (see https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html). The lock file in tsparser predates our workspace setup, I'll remove it
