### ISSUE TITLE
Not possible to add Description and Examples in the generate doc ?

### ISSUE THREAD

**Issue by nbdy-coder** [encoredev/encore#1298]
![image](https://github.com/user-attachments/assets/1f4d31bc-c6ba-431d-8ea8-3c9b28f9df14)

I'm trying to add examples following open api spec but it's not working.

Do you know why ? I don't find documentation to manage this

**Comment by marcuskohlberg** [comment]
Hey @nbdy-coder, sorry for the trouble.
This uses Go Doc Comments standard to generate the documentation, see: https://tip.golang.org/doc/comment
