### ISSUE TITLE
How to build from source code?

### ISSUE THREAD

**Issue by goodforever** [encoredev/encore#13]
How to build from source code?

**Comment by eandre** [comment]
Hey @goodforever! You can build `encore` from source using `go build ./cli/cmd/encore`.

To actually run it you'll need to point it at the location for the `encore.dev` runtime implementation as well as the Encore GOROOT. You can see the instructions for that here: [https://github.com/encoredev/encore/blob/main/DEVELOPING.md](DEVELOPING.md)

The Encore GOROOT is built from [https://github.com/encoredev/go](github.com/encoredev/go) and uses the regular Go build process (run `src/make.bash` or equivalent).

I'll add some better instructions to `DEVELOPING.md` to explain this. Thanks!

**Comment by sopta** [comment]
Hey @eandre. I just checked both links but none of them work.

**Comment by marcuskohlberg** [comment]
@sopta Thanks for flagging. There seems to be a sneaky bug in Github where is modifies the link url and adds "/issues/". If you copy the plain text url from Andrés comment and paste, it will work.
