### ISSUE TITLE
`console.log` is not behaving correctly

### ISSUE THREAD

**Issue by duckception** [encoredev/encore#1308]
Hey, there's a bug in how Encore handles `console.log` which made me scratch my head for a few good hours before I figured out that this wasn't an issue in my code.

Whenever you want to log an inline object, the log is not present in the terminal at all.

See this example:
```ts
export const hello = api(
  { expose: true,  path: "/hello/:name", method: "GET" },
  async ({ name }: { name: string }): Promise<{ message: string }> => {
    const message = `Hello, ${name}!`

    console.log('message1', message)     // ✅
    console.log({ message2: message })   // ❌ This is not being displayed.
    console.log('message3', { message }) // ✅

    return { message }
  }
)
```

Terminal output:

![image](https://github.com/user-attachments/assets/904f8930-037f-41a5-9b08-71dfd88ce30a)

**Comment by fredr** [comment]
Thanks for reporting, I've been able to reproduce this and have a fix up. 
However, it is recommended to use the built in logger for logging over using console.log:

```
import log from "encore.dev/log";
log.debug("some message", { hello: "world" })
```

**Comment by eandre** [comment]
We should note that one of the big benefits of using `encore.dev/log` is that it automatically includes information about the current request being processed, and also automatically adds the log message to the trace.

**Comment by duckception** [comment]
Definitely `encore.dev/log` is a way to go on production. I'm just so used to using `console.log` during development that this habit is kinda hard to overcome. One added benefit of using `console.log` during debugging is that it's way easier to see in the logs, but that's just my personal opinion. Thanks for the fix!
