### ISSUE TITLE
[ERROR]: `encore eject docker <DOCKER_IMAGE_TAG>`

### ISSUE THREAD

**Issue by ImBIOS** [encoredev/encore#1316]
### What I got

```sh
󰀵  󱑍 14:49  ﱮ encore-nextjs/backend    main !?+27 via 🥟 v1.1.22 via  v20.15.1   8s 
 ➜  docker context ls                
NAME            DESCRIPTION                               DOCKER ENDPOINT                                   ERROR
default *       Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                       
desktop-linux   Docker Desktop                            unix:///home/imbios/.docker/desktop/docker.sock   

󰀵  󱑍 14:49  ﱮ encore-nextjs/backend    main !?+27 via 🥟 v1.1.22 via  v20.15.1 
 ➜  encore eject docker encore-nextjs
2:49PM INF compiling Encore application for linux/amd64
2:49PM INF saving image to local docker daemon
2:49PM ERR unable to save docker image error="error loading image: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"
```

### What I expect

- Successfully build the docker image. 

### Encore Version

encore version v1.39.3

### Suspected Root Cause

The code which thrown the error:

https://github.com/encoredev/encore/blob/f8b785d73b213e01f25bbef44bccc5928b26d7e5/cli/daemon/export/export.go#L133-L147

Which from:

https://github.com/google/go-containerregistry/blob/b8e87ed57b8042c56cc4875aa99e79906b7b9ad5/pkg/v1/daemon/write.go#L66-L70

Suspected related issues:

- https://github.com/google/go-containerregistry/issues/205
- https://github.com/google/go-containerregistry/issues/552
- https://github.com/google/go-containerregistry/issues/627

### Command

```sh
encore eject docker encore-nextjs
```

### Tried Potential Solution

1. After identified the selected docker context is `dsktop-linux` and it's mismatch with the error given by encore, I switched it to `default`, and the error still the same.
2. After that, I thought it's similar to #1309, so I restarted my Ubunut machine, but error still there.

Let me know if there any other info you need.

**Comment by ImBIOS** [comment]
By the way, it's out of topic, but... @encoredev why don't you have a bug/feature GitHub issue template in place?

**Comment by eandre** [comment]
Sorry, but I'm not quite sure how to reproduce. As far as I can tell we're using `google/go-containerregistry` correctly, and it works fine on all the machines I have access to. Might be a permission issue with the socket or something. Have you filed an issue with go-containerregistry? They might be better equipped to help you figure out the root cause.

**Comment by ImBIOS** [comment]
Well, let me debug myself and document it here, maybe it will help someone out there trying to "give a shot" for @encoredev.

It turns out `docker version` also throws the same error,

```
󰀵  󱑍 14:27  ﱮ encore-nextjs/backend    main !?+27 via 🥟 v1.1.24 via  v20.15.1 
 ✗  docker version            
Client: Docker Engine - Community
 Version:           27.1.2
 API version:       1.46
 Go version:        go1.21.13
 Git commit:        d01f264
 Built:             Mon Aug 12 11:50:54 2024
 OS/Arch:           linux/amd64
 Context:           default
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

It means my docker is messed up from the beginning. Even though I following the official docs for Docker Desktop on Ubuntu 24.04 Noble Nimbus.

**Comment by ImBIOS** [comment]
Meme isn't violating CoC or Contributor Guideline, right?

![image](https://github.com/user-attachments/assets/ff069eae-3069-496d-b802-91c927820b39)

**Comment by ImBIOS** [comment]
@dacom-dark-sun MacOS? Mine happens in Ubuntu 24.04.

Are you using Orbstack for your docker? they use different `docker context`. It might be the root problem for you.

**Comment by ImBIOS** [comment]
- https://github.com/google/go-containerregistry/issues/1999

We can continue track this problem here

**Comment by ImBIOS** [comment]
Solved with this:
- https://forums.docker.com/t/docker-desktop-error-cannot-connect-to-the-docker-daemon-at-unix-var-run-docker-sock-is-the-docker-daemon-running/138438/5?u=imbios
