### ISSUE TITLE
Downloaded CLI, run encore app create and get errors when running encore run

### ISSUE THREAD

**Issue by jimzord12** [encoredev/encore#1392]
Greetings,

I saw your framework both on DEV and on Traversy Media Youtube Channel so I wanted to test it out.

I am using Windows 11 Pro ver. 10.022631 Build 22631

As mentioned in the title, I just followed the steps described at Quick Start Guide. 

This is the error I am getting. (I ran it using powershell 7.4.5 both as Admin and simple user)

 PS C:\Users\...\playing-with-encore\google-forms-manager> encore run
  ⠋ Building Encore application graph...
  ⠋ Analyzing service topology...
setup deps

Caused by:
    0: setup dependencies
    1: unable to symlink local encore.dev
    2: symlink encore.dev directory at "C:\\Users\\jimzord12\\GitHub\\playing-with-encore\\google-forms-manager\\node_modules\\encore.dev"
    3: A required privilege is not held by the client. (os error 1314)

Stack backtrace:
   0: anyhow::backtrace::capture::Backtrace::capture
   1: encore_tsparser::builder::package_mgmt::symlink_encore_dev
   2: <encore_tsparser::builder::package_mgmt::NpmPackageManager as encore_tsparser::builder::package_mgmt::PackageManager>::setup_deps
   3: scoped_tls::ScopedKey<T>::set
   4: tsparser_encore::main
   5: std::sys_common::backtrace::__rust_begin_short_backtrace
   6: main
   7: __tmainCRTStartup
   8: mainCRTStartup
   9: <unknown>
  10: <unknown>
  
  Its kinda sad as I was really excited to test it out, I guess I'll try Bun + Elysia and give Encore.ts a go later
  
  Best Regards

**Comment by fredr** [comment]
Hey! You need to enable developer mode on windows to get symlinking to work properly, see the answer here: https://github.com/encoredev/encore/discussions/1340

**Comment by eandre** [comment]
We're working around this issue in #1401, due to be released today. Thanks for reporting!

**Comment by sysmat** [comment]
```
iwr https://encore.dev/install.ps1 | iex
```

- error nothing installed
