### ISSUE TITLE
Pub/Sub subscription not removed

### ISSUE THREAD

**Issue by andrewgarner** [encoredev/encore#1412]
When removing a pub/sub subscription in a release the associated GCP infrastructure was not removed.

I can see the following in the cleanup logs for the deploy:

```
11:10:53.502ZINF Starting modify of Subscription (my-topic-0bf4970c.foobar-0aa252cf)
11:10:53.504ZDBG Waiting on modify of Subscription (my-topic-0bf4970c.foobar-0aa252cf): failed to get node status: no rows in result set
11:10:53.982ZINF Finished modify of env_13onjccb0mg8dpkcd7ig
11:11:03.482ZINF Finished modify of Subscription (my-topic-0bf4970c.foobar-0aa252cf)
```

**Comment by eandre** [comment]
Hey @andrewgarner! This is intended for safety reasons, as subscriptions are stateful and contain messages. They currently get marked as unused by Encore, but not deleted. We plan to add support for triggering deletion of unused stateful resources (like Pub/Sub subscriptions, databses, etc.) in the near term. Until then we recommend deleting it manually in GCP. Hope that helps!
