### ISSUE TITLE
Failed: error: object not found: Passport

### ISSUE THREAD

**Issue by Thr0TT1e** [encoredev/encore#1453]
Hi everyone, I just started to learn Encore and decided to use Prisma ORM (PostgreSQL). Here is a sample code that caused me an unsolvable problem:

```ts
import { PrismaClient, type Passport } from '@prisma/client';
import { api } from 'encore.dev/api';

const prisma = new PrismaClient();

export interface PassportParams {
  passport_id: string;
}

export interface CombinedParams {
  passport_id: string;
  body: PassportBody;
}

export interface PassportBody {
  passport_series: number;
  passport_number: number;
  passport_date: string;
  user_id: string;
}

export const getPassports = api(
  { method: 'GET', path: '/passports', expose: true },
  async (): Promise<Passport[]> => {
    try {
      const list = await prisma.passport.findMany();

      return list;
    } catch (error) {
      return [];
    }
  }
);

export const addPassport = api<PassportBody>(
  { method: 'POST', path: '/passports', expose: true },
  async (data): Promise<{ data: PassportResponse | boolean }> => {
    console.log('body', data);

    try {
      const passport = await prisma.passport.create({
        data,
      });

      if (passport.passport_id) {
        return { data: passport };
      }

      return { data: false };
    } catch (error) {
      return { data: false };
    }
  }
);

export const searchPassport = api<PassportBody, void>(
  { method: 'POST', path: '/passports/search', expose: true },
  async body => {
    console.log('body', body);
  }
);

export const getPassportById = api<PassportParams, void>(
  { method: 'GET', path: '/passports/:passport_id', expose: true },
  async ({ passport_id }) => {
    console.log('passport_id', passport_id);
  }
);

export const updatePassport = api<CombinedParams, void>(
  { method: 'PATCH', path: '/passports/:passport_id', expose: true },
  async ({ passport_id, body }) => {
    console.log('passport_id', passport_id);
    console.log('body', body);
  }
);

export const delPassport = api<PassportParams, void>(
  { method: 'DELETE', path: '/passports/:passport_id', expose: true },
  async ({ passport_id }) => {
    console.log('passport_id', passport_id);
  }
);

```

But I can't understand the error that appears:
```sh
❯ encore run
  ❌ Building Encore application graph... Failed: error: object not found: Passport
 --> /run/media/lobasov/etc/coding/gonetc/passport-service/passport/passport.ts:1:24
  |
1 | import { PrismaClient, type Passport } from '@prisma/client';
  |                        ^^^^^^^^^^^^^
error: unknown identifier
  --> /run/media/lobasov/etc/coding/gonetc/passport-service/passport/passport.ts:56:21
   |
56 |   async (): Promise<Passport[]> => {
   |                     ^^^^^^^^
expected named interface type, found Array(Basic(Never))
Stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: __libc_start_main
  11: <unknown>
Stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: __libc_start_main
   6: <unknown>
  ⠙ Analyzing service topology... 
error: object not found: Passport
 --> /run/media/lobasov/etc/coding/gonetc/passport-service/passport/passport.ts:1:24
  |
1 | import { PrismaClient, type Passport } from '@prisma/client';
  |                        ^^^^^^^^^^^^^


error: unknown identifier
  --> /run/media/lobasov/etc/coding/gonetc/passport-service/passport/passport.ts:56:21
   |
56 |   async (): Promise<Passport[]> => {
   |                     ^^^^^^^^


expected named interface type, found Array(Basic(Never))

Stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: __libc_start_main
  11: <unknown>

Stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: __libc_start_main
   6: <unknown>
```

Can you tell me where to dig?!

The following error occurs in the `addPassport` function if I make the response a separate interface:
```ts
interface PassportResponse {
  passport_id: string;
  passport_timestamp: Date;
  passport_series: number;
  passport_number: number;
  passport_date: Date;
  department: string;
  department_code: number;
  passport_status: string;
  user_id: string;
}
```
Error:
```sh
❯ encore run
  ❌ Building Encore application graph... Failed: error: unknown identifier
  --> /run/media/lobasov/etc/coding/gonetc/passport-service/passport/passport.ts:36:23
   |
36 |   passport_timestamp: Date;
   |                       ^^^^
error: unknown identifier
  --> /run/media/lobasov/etc/coding/gonetc/passport-service/passport/passport.ts:42:18
   |
42 |   passport_date: Date;
   |                  ^^^^
error: unsupported basic type in schema: Never
  ⠙ Analyzing service topology... 
error: unknown identifier
  --> /run/media/lobasov/etc/coding/gonetc/passport-service/passport/passport.ts:36:23
   |
36 |   passport_timestamp: Date;
   |                       ^^^^


error: unknown identifier
  --> /run/media/lobasov/etc/coding/gonetc/passport-service/passport/passport.ts:42:18
   |
42 |   passport_date: Date;
   |                  ^^^^


error: unsupported basic type in schema: Never
```

**Comment by eshimischi** [comment]
It has nothing to do with Encore.ts. You need to understand the principles of https://www.prisma.io/docs/orm/prisma-client/setup-and-configuration/introduction and also Typescript, i think you have issues with configs

**Comment by Thr0TT1e** [comment]
The `type Passport` is generated from the model defined in the schema. Here's a screenshot:

![изображение](https://github.com/user-attachments/assets/4a2f171b-d6a1-4d03-8680-5c4d15cd2d91)

Here is an example of a prisma ORM schema:

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Passport {
  passport_id                  String        @id @default(uuid()) @db.Uuid
  passport_timestamp  DateTime @default(now()) @db.Timestamp(6)
  passport_status          String        @db.VarChar(100)
  passport_series          Int
  passport_number      Int
  passport_date            DateTime  @db.Timestamp(6)
  department                String         @db.VarChar(200)
  department_code      Int
  user_id                         String        @db.Uuid

  @@index([user_id])
}
```

**Comment by eshimischi** [comment]
> The `type Passport` is generated from the model defined in the schema. Here's a screenshot:
> 
> ![изображение](https://private-user-images.githubusercontent.com/37178902/374052364-4a2f171b-d6a1-4d03-8680-5c4d15cd2d91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyODMxMjksIm5iZiI6MTcyODI4MjgyOSwicGF0aCI6Ii8zNzE3ODkwMi8zNzQwNTIzNjQtNGEyZjE3MWItZDZhMS00ZDAzLTg2ODAtNWM0ZDE1Y2QyZDkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDA2MzM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3ZDM1NDMwNGI5MTkxYTQ1Y2E3ZjU5Y2MxODM0Yjg5ZDg4ZTlkYTg3MTBjZDIwN2QyMjBiN2RiNTJjYThjZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZDbs8M3JZ1hwR-HjSGaRvJkmbZaBiUH0fohBBE0P44A)
> 
> Here is an example of a prisma ORM schema:
> 
> ```prisma
> generator client {
>   provider = "prisma-client-js"
> }
> 
> datasource db {
>   provider = "postgresql"
>   url      = env("DATABASE_URL")
> }
> 
> model Passport {
>   passport_id        String   @id @default(uuid()) @db.Uuid
>   passport_timestamp DateTime @default(now()) @db.Timestamp(6)
>   passport_status    String   @db.VarChar(100)
>   passport_series    Int
>   passport_number    Int
>   passport_date      DateTime @db.Timestamp(6)
>   department         String   @db.VarChar(200)
>   department_code    Int
>   user_id            String   @db.Uuid
> 
>   @@index([user_id]) 
> }
> ```
> 
> [prisma.io/docs/orm/prisma-schema/data-model/models#optional-and-mandatory-fields](https://www.prisma.io/docs/orm/prisma-schema/data-model/models#optional-and-mandatory-fields)
> 
> > Prisma Client: Prisma Client's generated [TypeScript types](https://www.prisma.io/docs/orm/prisma-schema/data-model/models#type-definitions) that represent the models in your application code will also define these fields as required to ensure they always carry values at runtime.

https://www.prisma.io/docs/orm/prisma-client/setup-and-configuration/generating-prisma-client

Okay, but you should import it not from @prisma/client, but from generated prosma model then! You don’t have type Passport in @prisma/client, again!

**Comment by Thr0TT1e** [comment]
Ok, let's say we don't use import of types from prism, we make our own interface description. And I don't understand why the error occurs:
```ts
interface PassportResponse {
  passport_id: string;
  passport_timestamp: Date;
  passport_series: number;
  passport_number: number;
  passport_date: Date;
  department: string;
  department_code: number;
  passport_status: string;
  user_id: string;
}
```
Error:
```sh
❯ encore run
  ❌ Building Encore application graph... Failed: error: unknown identifier
  --> /run/media/lobasov/etc/coding/gonetc/passport-service/passport/passport.ts:36:23
   |
36 |   passport_timestamp: Date;
   |                       ^^^^
error: unknown identifier
  --> /run/media/lobasov/etc/coding/gonetc/passport-service/passport/passport.ts:42:18
   |
42 |   passport_date: Date;
   |                  ^^^^
error: unsupported basic type in schema: Never
  ⠙ Analyzing service topology... 
error: unknown identifier
  --> /run/media/lobasov/etc/coding/gonetc/passport-service/passport/passport.ts:36:23
   |
36 |   passport_timestamp: Date;
   |                       ^^^^


error: unknown identifier
  --> /run/media/lobasov/etc/coding/gonetc/passport-service/passport/passport.ts:42:18
   |
42 |   passport_date: Date;
   |                  ^^^^


error: unsupported basic type in schema: Never
```

**Comment by eshimischi** [comment]
> Ok, let's say we don't use import of types from Prisma ORM, we make our own interface description. And I don't understand why the error occurs:
> 
> ```ts
> interface PassportResponse {
>   passport_id: string;
>   passport_timestamp: Date;
>   passport_series: number;
>   passport_number: number;
>   passport_date: Date;
>   department: string;
>   department_code: number;
>   passport_status: string;
>   user_id: string;
> }
> ```
> 
> Error:
> 
> ```shell
> ❯ encore run
>   ❌ Building Encore application graph... Failed: error: unknown identifier
>   --> /run/media/lobasov/etc/coding/gonetc/passport-service/passport/passport.ts:36:23
>    |
> 36 |   passport_timestamp: Date;
>    |                       ^^^^
> error: unknown identifier
>   --> /run/media/lobasov/etc/coding/gonetc/passport-service/passport/passport.ts:42:18
>    |
> 42 |   passport_date: Date;
>    |                  ^^^^
> error: unsupported basic type in schema: Never
>   ⠙ Analyzing service topology... 
> error: unknown identifier
>   --> /run/media/lobasov/etc/coding/gonetc/passport-service/passport/passport.ts:36:23
>    |
> 36 |   passport_timestamp: Date;
>    |                       ^^^^
> 
> 
> error: unknown identifier
>   --> /run/media/lobasov/etc/coding/gonetc/passport-service/passport/passport.ts:42:18
>    |
> 42 |   passport_date: Date;
>    |                  ^^^^
> 
> 
> error: unsupported basic type in schema: Never
> ```

Create your repo here on Github and let's discuss it there instead of Encore issues. Because it has nothing to do with it.

**Comment by kamtoeddy** [comment]
Hi, I faced this problem and I observed that the error occurs when importing types/interfaces from other files.

```ts
// ❌ this will fail
export { siteChecksDb, type SiteStatus };

// ✅ this works
export type SiteStatus = {
  id: number;
  site_id: number;
  up: boolean;
  checked_at: string;
};

// ✅ this also works
export interface SiteStatus {
  id: number;
  site_id: number;
  up: boolean;
  checked_at: string;
};
```

**Comment by ptl-miguel** [comment]
Hey @Thr0TT1e you ever find a solution to this issue?

**Comment by Thr0TT1e** [comment]
> Hey @Thr0TT1e you ever find a solution to this issue?

Solving this problem will not be an easy way. The whole point is in defining the Encore\types.

At the first approximation in the parser https://github.com/encoredev/encore/blob/88e15a6e4a73de0011a5e83b3ee5cd124424cc51/tsparser/src/parser/types/typ.rs#L17-L45 this type is not provided: https://github.com/encoredev/encore/blob/88e15a6e4a73de0011a5e83b3ee5cd124424cc51/tsparser/src/parser/types/typ.rs#L107-L120.

The substitution attempt for a string like 'Date' also failed.

For this reason, Encore\has been abandoned at the moment. But the project is really interesting and I hope that we will return to it soon.

**Comment by fredr** [comment]
We are adding date support to typescript, it will be available soon! See https://github.com/encoredev/encore/pull/1504

**Comment by ptl-miguel** [comment]
> > Hey @Thr0TT1e you ever find a solution to this issue?
> 
> Solving this problem will not be an easy way. The whole point is in defining the Encore\types.
> 
> At the first approximation in the parser
> 
> https://github.com/encoredev/encore/blob/88e15a6e4a73de0011a5e83b3ee5cd124424cc51/tsparser/src/parser/types/typ.rs#L17-L45
> 
> this type is not provided:
> https://github.com/encoredev/encore/blob/88e15a6e4a73de0011a5e83b3ee5cd124424cc51/tsparser/src/parser/types/typ.rs#L107-L120
> 
> .
> The substitution attempt for a string like `Date` also failed.
> 
> For this reason, Encore\has been abandoned at the moment. But the project is really interesting and I hope that we will return to it soon.

I see, thank you for the response!

**Comment by eandre** [comment]
Dates are now supported in Encore v1.43. Please give it a go and let us know if the issue has been resolved!

**Comment by Thr0TT1e** [comment]
All right. I'll try to get to the project over the weekend and try.

Additionally unsubscribe.

**Comment by Thr0TT1e** [comment]
Dear colleagues, I apologize for the delay. I checked how encore works with the Date data type, and everything works correctly.

Thank you for your prompt work!

**Comment by fredr** [comment]
Perfect, thank you for checking! I'll close this issue as it is resolved as far as I understand.
