### ISSUE TITLE
Incomplete file path when generating js in Typescript

### ISSUE THREAD

**Issue by zarubto4** [encoredev/encore#1467]
Encore service is defined as "**encore.service.ts**" and everything is fine.
When you make the API in the file "**api.ts**" everything is fine again. For cross-service calls between each other
But when you do "**api.controller.ts**"  the encore doesn't generate the file path correctly.  The compiler works, the code also works and can be delivered to production, but typescript has a problem with it.

Typescript original Folder
![Snímek obrazovky 2024-10-11 v 7 44 10](https://github.com/user-attachments/assets/be1f4f92-6210-44a1-bc35-fffcfffb3c76)
![Snímek obrazovky 2024-10-11 v 7 44 44](https://github.com/user-attachments/assets/7cefbdd2-0856-44e9-b94a-34f12d61059c)

**Manual fixed in "endpoint.d.ts"**
![Snímek obrazovky 2024-10-11 v 7 45 19](https://github.com/user-attachments/assets/470a765d-f5c6-4c3b-b8d5-d38620f2cd6c)
- But you lose it every time you compile

**Comment by eandre** [comment]
Ah great catch. We're stripping the file extension and it's being too greedy. Will fix shortly.

**Comment by zarubto4** [comment]
Just a question - @eandre 
controller with Api must be in folder in same level as encore.serviice.ts yes? 
Because if you move it into folder,  file "endpoints" is completely empty.  
![Snímek obrazovky 2024-10-14 v 14 01 37](https://github.com/user-attachments/assets/b9632285-14ab-44e4-8e3f-deaba08e003d). 

If its not a feature, then its a bug and i can report it separately.

**Comment by eandre** [comment]
It should be fine to have it in a subdirectory. I've tested that and it works fine on my end, at least with the fix in #1480. Let me know if that doesn't work on your end in the next release.
