### ISSUE TITLE
`encore gen client` with `--lang=openapi` adds properties as required for Go when they are not required

### ISSUE THREAD

**Issue by echarrod** [encoredev/encore#1477]
Let's say I have a Go struct:
```go
type User struct {
	ID          int64     `json:"id,omitempty" validate:"required"`
	Email       string ` json:"email,omitempty"`
}
```

If this struct is fed into the openAPI generator, e.g. with:
```shell
encore gen client --env=local --lang=openapi --output=gen/openapi.json
```
Then the output openapi.json has _all_ the fields marked as required:
```json
 "users.User": {
...
 "required": [
          "id",
          "email",
...
```

I see at https://github.com/encoredev/encore/blob/00f2f03a3f1d6ba01c0b0b2aac12a4f6af4ddf5a/internal/clientgen/openapi/schema.go#L65-L67 that we set the fields as required if they are *not* optional. I presume this works fine for TypeScript with optional fields, but could we switch on the source language, and only add required to Go if the field has the `validate:"required"` annotation (or similar)?

Happy to provide more details if required.
Thanks

**Comment by murilopl** [comment]
Hi @echarrod ,
try using `encore:"optional"` tag.
Example:
```go
type Event struct {
	Message string `json:"message" encore:"optional"`
}
```

**Comment by echarrod** [comment]
Ah thanks @murilopl, didn't know about that tag! Can't see it in the docs either. Have tried it though and it does remove them from required, thanks!

**Comment by echarrod** [comment]
Do you think I should add this to https://encore.dev/docs/primitives/apis#request-and-response-schemas, or is it not that common to need this, and might inflate the docs?

**Comment by eandre** [comment]
It should definitely be documented, that's an oversight! Yes, that looks like the right place.
