### ISSUE TITLE
feature request: add configuration for the dashboard address.

### ISSUE THREAD

**Issue by laurencefass** [encoredev/encore#1490]
im testing encore in a deban bullseye docker container as I dont want to install on my host while Im evaluating it

ive run the basic hello world app.

By default encore runs its processed on 127.0.0.1 which is not useful for exposing docker ports

For the REST API I can change with encure run --listen 0.0.0.0:4000 which correctly exposes the port.

How do I change the dasboard address?

There dont seem to be many options to customise execution at present. Generally (coming from nest js) it feels like there is a large section on configuration missing from the encore docs.

**Comment by fredr** [comment]
You can set the dashboard listen address via `ENCORE_DEVDASH_LISTEN_ADDR`, e.g `ENCORE_DEVDASH_LISTEN_ADDR=0.0.0.0:9400 encore run`

**Comment by laurencefass** [comment]
great! thank you.
