### ISSUE TITLE
starter template installation incomplete with build errors - problem with encore.dev installation

### ISSUE THREAD

**Issue by laurencefass** [encoredev/encore#1494]
UPDATE: I have repeated the installation a few times trying to see why these projects are working in a non-standard way and now I can see why TS path resolution does not work. Installing any of the templates creates an encore.dev FILE in node_modules. I have never seen this before. It gets more interesting: when I click on the file VSCODE says "file not found"!

![image](https://github.com/user-attachments/assets/3dc678aa-4d4b-4ffd-8a65-133f094ed479)

Until I noticed this (after several repeated installs looking for clues)  I tried installing the "missing" encore.dev which resovles the TS paths but seems to disappear on each run! 

The app somehow runs with "encore run"  but intellisense cannot resolve pathnames. I dont know how it does this without an encore.dev node_modules and a file of ths same name that cant be accessed!

Not being able to resolve paths in Typecript makes development very difficult. As a project matures its hard for developers to keep documentation updated and its essential to be able to view actual code, types and interfaces by following links to understand typescript errors. I dont entirely understand how the imports work from the encore.dev file (rather than a well formed node_modules folder). 

original post follows.

===

Im trialling encore.ts for the first time and following the intro guide

https://encore.dev/docs/quick-start

Im installing on debian linux bullseye and I've repeated the installation a few times to ensure consistency reaching same result each time, the installation template doesnt install encore.dev so its not possible for IDE to resolve typescript imports property (though they seem to build?).

I picked the simple REST API template. The build steps in the docs are incomplete  (it needs an npm install to manually install encore.dev!?) and the build has quite a lot of errors. 

This is the template generated package.json file:

```
{
  "name": "encore-ts-starter",
  "private": true,
  "version": "0.0.1",
  "description": "Encore Typescript Starter",
  "license": "MPL-2.0",
  "type": "module",
  "scripts": {
    "test": "vitest"
  },
  "devDependencies": {
    "@types/node": "^20.5.7",
    "typescript": "^5.2.2",
    "vitest": "^1.5.0"
  },
  "dependencies": {
    "encore.dev": "^1.41.14"
  },
  "optionalDependencies": {
    "@rollup/rollup-linux-x64-gnu": "^4.13.0"
  }
}
```

General Observations

The template does not install encore.dev(?) so import { api } from "encore.dev/api"; does not resolve properly because encode.dev.

![image](https://github.com/user-attachments/assets/92279ffe-afcc-4067-91b7-b2fc75f1ae2a)

i fixed this with a manual install. 

![image](https://github.com/user-attachments/assets/69f1779c-d1fb-46e4-ad7e-1dda490c6508)

I checked the integrity of the build with tsc before working further with the code:

```
root@encoretsc:/apps/testbuild/test# npx tsc --noEmit
node_modules/encore.dev/api/gateway.ts:8:25 - error TS2694: Namespace '"/apps/testbuild/test/node_modules/encore.dev/internal/runtime/mod"' has no exported member 'Gateway'.

8   private impl: runtime.Gateway;
                          ~~~~~~~

node_modules/encore.dev/api/gateway.ts:17:28 - error TS2694: Namespace '"/apps/testbuild/test/node_modules/encore.dev/internal/runtime/mod"' has no exported member 'Request'.

17       auth = (req: runtime.Request) => {
                              ~~~~~~~

node_modules/encore.dev/internal/api/node_http.ts:20:25 - error TS2694: Namespace '"/apps/testbuild/test/node_modules/encore.dev/internal/runtime/mod"' has no exported member 'BodyReader'.

20   private body: runtime.BodyReader;
                           ~~~~~~~~~~

node_modules/encore.dev/internal/api/node_http.ts:21:24 - error TS2694: Namespace '"/apps/testbuild/test/node_modules/encore.dev/internal/runtime/mod"' has no exported member 'Request'.

21   private req: runtime.Request;
                          ~~~~~~~

node_modules/encore.dev/internal/api/node_http.ts:23:28 - error TS2694: Namespace '"/apps/testbuild/test/node_modules/encore.dev/internal/runtime/mod"' has no exported member 'Request'.

23   constructor(req: runtime.Request, body: runtime.BodyReader) {
                              ~~~~~~~

node_modules/encore.dev/internal/api/node_http.ts:23:51 - error TS2694: Namespace '"/apps/testbuild/test/node_modules/encore.dev/internal/runtime/mod"' has no exported member 'BodyReader'.

23   constructor(req: runtime.Request, body: runtime.BodyReader) {
                                                     ~~~~~~~~~~

node_modules/encore.dev/internal/api/node_http.ts:86:26 - error TS2694: Namespace '"/apps/testbuild/test/node_modules/encore.dev/internal/runtime/mod"' has no exported member 'RequestMeta'.

86   private _meta: runtime.RequestMeta | undefined;
                            ~~~~~~~~~~~

node_modules/encore.dev/internal/api/node_http.ts:87:31 - error TS2694: Namespace '"/apps/testbuild/test/node_modules/encore.dev/internal/runtime/mod"' has no exported member 'RequestMeta'.

87   private get meta(): runtime.RequestMeta {
                                 ~~~~~~~~~~~

node_modules/encore.dev/internal/api/node_http.ts:120:22 - error TS2694: Namespace '"/apps/testbuild/test/node_modules/encore.dev/internal/runtime/mod"' has no exported member 'ResponseWriter'.

120   private w: runtime.ResponseWriter;
                         ~~~~~~~~~~~~~~

node_modules/encore.dev/internal/api/node_http.ts:123:43 - error TS2694: Namespace '"/apps/testbuild/test/node_modules/encore.dev/internal/runtime/mod"' has no exported member 'ResponseWriter'.

123   constructor(req: RawRequest, w: runtime.ResponseWriter) {
                                              ~~~~~~~~~~~~~~

node_modules/encore.dev/internal/appinit/mod.ts:6:31 - error TS2694: Namespace '"/apps/testbuild/test/node_modules/encore.dev/internal/runtime/mod"' has no exported member 'ApiRoute'.

6 export type Handler = runtime.ApiRoute;
                                ~~~~~~~~

node_modules/encore.dev/internal/appinit/mod.ts:26:27 - error TS2694: Namespace '"/apps/testbuild/test/node_modules/encore.dev/internal/runtime/mod"' has no exported member 'Stream'.

26   private stream: runtime.Stream;
                             ~~~~~~

node_modules/encore.dev/internal/appinit/mod.ts:28:31 - error TS2694: Namespace '"/apps/testbuild/test/node_modules/encore.dev/internal/runtime/mod"' has no exported member 'Stream'.

28   constructor(stream: runtime.Stream) {
                                 ~~~~~~

node_modules/encore.dev/internal/appinit/mod.ts:48:27 - error TS2694: Namespace '"/apps/testbuild/test/node_modules/encore.dev/internal/runtime/mod"' has no exported member 'Socket'.

48   private socket: runtime.Socket;
                             ~~~~~~

node_modules/encore.dev/internal/appinit/mod.ts:50:31 - error TS2694: Namespace '"/apps/testbuild/test/node_modules/encore.dev/internal/runtime/mod"' has no exported member 'Socket'.

50   constructor(socket: runtime.Socket) {
                                 ~~~~~~

node_modules/encore.dev/internal/appinit/mod.ts:82:30 - error TS2694: Namespace '"/apps/testbuild/test/node_modules/encore.dev/internal/runtime/mod"' has no exported member 'Request'.

82       handler: (req: runtime.Request, stream: unknown) => {
                                ~~~~~~~

node_modules/encore.dev/internal/appinit/mod.ts:86:39 - error TS2339: Property 'Stream' does not exist on type 'typeof import("/apps/testbuild/test/node_modules/encore.dev/internal/runtime/mod")'.

86         if (stream instanceof runtime.Stream) {
                                         ~~~~~~

node_modules/encore.dev/internal/appinit/mod.ts:89:39 - error TS2339: Property 'Socket' does not exist on type 'typeof import("/apps/testbuild/test/node_modules/encore.dev/internal/runtime/mod")'.

89         if (stream instanceof runtime.Socket) {
                                         ~~~~~~

node_modules/encore.dev/internal/appinit/mod.ts:106:22 - error TS2694: Namespace '"/apps/testbuild/test/node_modules/encore.dev/internal/runtime/mod"' has no exported member 'Request'.

106         req: runtime.Request,
                         ~~~~~~~

node_modules/encore.dev/internal/appinit/mod.ts:107:23 - error TS2694: Namespace '"/apps/testbuild/test/node_modules/encore.dev/internal/runtime/mod"' has no exported member 'ResponseWriter'.

107         resp: runtime.ResponseWriter,
                          ~~~~~~~~~~~~~~

node_modules/encore.dev/internal/appinit/mod.ts:108:23 - error TS2694: Namespace '"/apps/testbuild/test/node_modules/encore.dev/internal/runtime/mod"' has no exported member 'BodyReader'.

108         body: runtime.BodyReader
                          ~~~~~~~~~~

node_modules/encore.dev/internal/appinit/mod.ts:119:28 - error TS2694: Namespace '"/apps/testbuild/test/node_modules/encore.dev/internal/runtime/mod"' has no exported member 'Request'.

119     handler: (req: runtime.Request) => {
                               ~~~~~~~

node_modules/encore.dev/internal/reqtrack/mod.ts:16:48 - error TS2694: Namespace '"/apps/testbuild/test/node_modules/encore.dev/internal/runtime/mod"' has no exported member 'Request'.

16 export function setCurrentRequest(req: runtime.Request) {
                                                  ~~~~~~~

node_modules/encore.dev/internal/reqtrack/mod.ts:20:46 - error TS2694: Namespace '"/apps/testbuild/test/node_modules/encore.dev/internal/runtime/mod"' has no exported member 'Request'.

20 export function getCurrentRequest(): runtime.Request | null {
                                                ~~~~~~~

node_modules/encore.dev/internal/runtime/mod.ts:2:25 - error TS2307: Cannot find module './napi/napi.cjs' or its corresponding type declarations.

2 import { Runtime } from "./napi/napi.cjs";
                          ~~~~~~~~~~~~~~~~~

node_modules/encore.dev/internal/runtime/mod.ts:4:15 - error TS2307: Cannot find module './napi/napi.cjs' or its corresponding type declarations.

4 export * from "./napi/napi.cjs";
                ~~~~~~~~~~~~~~~~~

Found 26 errors in 5 files.

Errors  Files
     2  node_modules/encore.dev/api/gateway.ts:8
     8  node_modules/encore.dev/internal/api/node_http.ts:20
    12  node_modules/encore.dev/internal/appinit/mod.ts:6
     2  node_modules/encore.dev/internal/reqtrack/mod.ts:16
     2  node_modules/encore.dev/internal/runtime/mod.ts:2
```

I hope this is useful.

**Comment by fredr** [comment]
If you `cd` into the created directory and run `encore run`, does all the errors disappear then? I think then `encore.dev` should be automatically added if its not there yet

**Comment by laurencefass** [comment]
these errors are created when i install the project. the install template is not adding encore.dev as a folder in node_modules.

somehow (I really dont understand how or why) the project runs! but there is no Typescript resolution unless I manually install with npm install, but this gets deleted when i run it (or so it seems)!

Im trying to understand what is happening: Is encore trying to replaced node folders with executables/binaries?

**Comment by laurencefass** [comment]
running the app with encore run did not remove the weird encore.dev file, nor did it create node_modules/encore.dev. I wouldnt have expected it to.

![image](https://github.com/user-attachments/assets/bbb43c17-89e0-4867-80e2-fb2ea83b431c)

**Comment by laurencefass** [comment]
confirming again that running npm install from the app folder removes the node_modules/encore.dev file and replaces it with a legitmate node_modules/encore.dev folder. This also fixes TS module resolution.

**Comment by fredr** [comment]
Are you having trouble with this on both windows and linux? or are these errors specifically for windows? 

On windows, if you havent already, you could try to enable developer mode to allow windows to create symlinks. After you've enalbed that, remove node_modules or create a fully new project at see if that works better.

To enable developer mode:
```
Settings > System > For developers > Developer mode
```

Would be interesting to see if that works better. We have a special case that create windows file junctions instead of symlinks if symlinks isnt allowed.

**Comment by laurencefass** [comment]
I am not developing on my host (Debian) and I dont develop code using Windows. I created a [linux sandbox](https://github.com/laurencefass/encore.ts/tree/main) to eliminate any local environment questions and have it run consistently anywhere. This will work on any Docker host. Im using Debian Bullseye base image as the smallest I could find with gc compatability. I have extended this with Docker CLI for the postgres demo which mounts the docker sock and encore spins up databases in the host correctly.

I can run the three apps concurrently - main app and dashboards. However all three containers have the same encore.dev resolvability issues and its not possible to develop without TS resolvability.

**Comment by laurencefass** [comment]
I can create symlinks from inside these containers. Thats expected as its just a debian o/s. 

```
root@encorechat:/apps/chat# ln -s encore.app link-to-encore.app
root@encorechat:/apps/chat# ls
README.md  chat  chat-room.png  encore.app  encore.gen  frontend  link-to-encore.app  node_modules  package-lock.json  package.json  tsconfig.json
```

**Comment by laurencefass** [comment]
Aside: I couldnt get it working in Alpine due to gc incompatability but it would be great to find a smaller gc compatible image than debian to run micro-instances of encore.

**Comment by laurencefass** [comment]
here are the stages. i am following the docs exactly not adding any extra steps until the npm install at the end.

The installation template is incorrectly generating something that looks like a file (but isnt) called encore.dev and is also placing a package-lock.json in node_modules. 

1. installing

![image](https://github.com/user-attachments/assets/1a07652d-1b2d-4966-a278-82ed6b77a981)

2. install complete (notice that encore.dev file in node_modules)

![image](https://github.com/user-attachments/assets/9fc3a298-05c2-4ce3-af79-a308c7cafa08)

3. app is running

![image](https://github.com/user-attachments/assets/8e98ebd1-0ec7-4fa8-9d22-63b285402087)

4. node_modules contains package-lock.json and encore.dev file! 

![image](https://github.com/user-attachments/assets/5b65f4ea-957d-4235-a9cb-43236687feea)

now adding a stage:

```
root@encorechat:/apps/chat# npm i

changed 1 package, and audited 190 packages in 2s

37 packages are looking for funding
  run `npm fund` for details

2 vulnerabilities (1 moderate, 1 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
```

result: encore.dev file removed, encore.dev folder correctly positioned, TS modules resolving correctly. 

![image](https://github.com/user-attachments/assets/e8129317-922a-4554-8a4b-4a98161e8968)

**Comment by laurencefass** [comment]
docker container approach should generate same result wherever its applied.

**Comment by fredr** [comment]
If you do a `ln -l encore.dev` is it a link that points to somewhere that doesn't exist?

fwiw I dont think anyone have tried to run the development environment in a container before, so there might be something strange going on because of that.

You can however export your application into a docker image that is suited for running in production, if you want to self host the application

**Comment by laurencefass** [comment]
im reinstalling so i can check the encore.dev symlink....

root@encorechat:/apps/chat/node_modules# pwd
/apps/chat/node_modules
root@encorechat:/apps/chat/node_modules# ls -l encore.dev
lrwxrwxrwx 1 root root 36 Oct 17 15:12 encore.dev -> /root/.encore/runtimes/js/encore.dev
root@encorechat:/apps/chat/node_modules# ls -la /root/.encore/runtimes/js
total 29760
drwxr-xr-x  3 1001 1001     4096 Oct 15 15:03 .
drwxr-xr-x  4 1001 1001     4096 Oct 15 15:03 ..
-rw-r--r--  1 1001 1001 30458600 Oct 15 15:03 encore-runtime.node
drwxr-xr-x 12 1001 1001     4096 Oct 15 15:03 encore.dev

so the symlink is pointing at the encore.dev file not the node file though both exist. 

Is that correct?

Interesting that you're not aware of anyone running this in docker. The dashboard address isnt configurable (as far as a I can tell) so I would be constrained to running a single dev server. With containers its easy to run multiple dev servers side by side without polluting my /root folder.

**Comment by laurencefass** [comment]
I want to self-host the dev server(s) and run production in the cloud.

**Comment by laurencefass** [comment]
Im still not sure if the encore.dev symlink is intentional and if so if its pointing at the right place. the files are present and the apps run so it works but its not standard npm so not sure how module resolution will work.

or... should the installation be creating a standard node_modules/encore.dev folder and something has gone wrong with the installation using my setup?

**Comment by eandre** [comment]
It is intentional, but perhaps we need to move away from this approach if it's not interacting well with editors. I think in your case it's probably causing problems in the editor because your editor is not running on the same filesystem as the code base, so it's not interpreting the symlinks correctly.

**Comment by laurencefass** [comment]
Im using vscode remote extensions and never had a problem with symlinks. 

Quick check that the extension interprets symlinks correctly I created a random symlink to braces folder looks ok.

![image](https://github.com/user-attachments/assets/e6e007fc-6a2f-4b81-89b7-c9dca7d7a3c9)

For a consistent dev experience (I think) encore.dev will need to resolve to a node_modules folder for intellisense to work. However it does appear to resolve correctly at runtime else the apps would throw errors and they're not.

**Comment by eandre** [comment]
IntelliSense works fine in normal circumstances, to be clear :)

**Comment by fredr** [comment]
> so the symlink is pointing at the encore.dev file not the node file though both exist.

its correct that it points to encore.dev, its a folder though, not an executable

**Comment by fredr** [comment]
Awesome! Glad you got it working
