### ISSUE TITLE
Is Drizzle ORM Work with Encore.dev ?

### ISSUE THREAD

**Issue by bright-coder** [encoredev/encore#1528]
I read the document [https://encore.dev/docs/ts/primitives/databases#orm-example](https://encore.dev/docs/ts/primitives/databases#orm-example) 

"Frameworks like [Prisma](https://www.prisma.io/) and [Drizzle](https://orm.drizzle.team/) are at the moment not supported by Encore. Encore uses plain SQL migration files for its migrations."

But Drizzle Document [https://orm.drizzle.team/docs/migrations](https://orm.drizzle.team/docs/migrations) tell that Option 3

"That’s a codebase first approach. You have your TypeScript Drizzle schema as a source of truth and Drizzle let’s you generate SQL migration files based on your schema changes with [drizzle-kit generate](https://orm.drizzle.team/docs/drizzle-kit-generate) and then apply them to the database with [drizzle-kit migrate](https://orm.drizzle.team/docs/drizzle-kit-migrate) commands."

Im only use command "drizzle-kit generate" to generate SQL migrations file and use command "encore run"
**It's work.**

or me misunderstand something.

**Comment by kanikanaik** [comment]
I did as you specified still I'm getting this error - 
HTTP 500 Internal Server Error: {"code":"internal","message":"An internal error occurred.","internal_message":"client is not a function","details":null}

**Comment by bright-coder** [comment]
@kanikanaik can u give me your code

**Comment by kanikanaik** [comment]
When I run migrations the tables are being created but I am getting this error when I am running a query.


> @kanikanaik can u give me your code

**Comment by benjick** [comment]
Encore is sponsoring Drizzle. Maybe it will be integrated

**Comment by marcuskohlberg** [comment]
Hey, we just improved Encore.ts' ORM support and have added support for Drizzle among others.
You can find the Drizzle docs here: https://encore.dev/docs/ts/develop/orms/drizzle
If you have any questions, join Discord and we'll help you out: https://encore.dev/discord
