### ISSUE TITLE
[BUG?] Issue parsing postgres ENUM types in rust daemon

### ISSUE THREAD

**Issue by nich-frai** [encoredev/encore#1546]
# [BUG?] Parsing custom postgres ENUM types in Rust daemon 
--------------------------------------------------------

## How to reproduce:
1. Create a migration using postgres native ENUM type:
```sql
CREATE TYPE some_enum as ENUM ('value1','value2','value3');
CREATE TABLE some_table (
 id SERIAL PRIMARY KEY,
 use_enum some_enum DEFAULT 'value1'
);
```

2. Use the native dabatabse client provided by encore
```ts
import { SQLDatabase } from "encore.dev/storage/sqldb";

export const db = new SQLDatabase("some_db", { migrations : "./migrations"});
```

3. Try to query using this connection/client
```ts
const row = db.queryRow`
SELECT 
      id, use_enum  
    FROM 
      some_table
`;
```

-----------------------------------------------------------------

At this point the rust daemon fails with the following message:
```
An internal error occurred.: unable to parse column use_enum: Error {
   kind: FromSql(0,),
   cause: Some( WrongType {
      postgres: Other(
         Other {
            name: \"use_enum\",
            oid: 16847,
            kind: Enum([
               \"value1\",
               \"value2\",
               \"value3\",
            ],),
            schema: \"public\",
        },
      ),
      rust: \"encore_runtime_core::sqldb::val::RowValue\",
   },),
}
```

Inserting into the table/database does not reproduce this error, only while parsing/selecting from it!

## Environment
- OS: Win11
- Encore version being used: v1.43.8
- Rustc version: rustc 1.82.0 
- Docker postgres image being used: encoredotdev/postgres:15

Just ask if any other information would help!

**Comment by mdauthentic** [comment]
I'm having a similar issue with postgres `Enum`. Mine failed with the following message.

```
[Error: error serializing parameter 1: cannot convert between the Rust type `encore_runtime_core::sqldb::val::RowValue` and the Postgres type `user_role`] {
  code: 'GenericFailure'
}
```

**Comment by eandre** [comment]
Thanks for the report. Will take a look at fixing this tomorrow. In the meantime you can work around it by casting the column to text `SELECT my_enum::text [...]`.

**Comment by eandre** [comment]
This is now fixed in Encore v1.44.5. Thanks for reporting!

**Comment by shuyangsun** [comment]
Hi @eandre, thank you for fixing this bug. Unfortunately, I'm encountering this issue again with v1.45.2. This is the error I'm getting: `Error: error serializing parameter 2: cannot convert between the Rust type encore_runtime_core::sqldb::val::RowValue and the Postgres type project_permission`.

Can you please take another look?

**Comment by fredr** [comment]
@shuyangsun please open a new issue about this, and add all the details like your sql schema etc, and we'll have a look
