### ISSUE TITLE
RabbitMQ Compatibility

### ISSUE THREAD

**Issue by sayyidyofa** [encoredev/encore#1553]
Encore currently supports the following Pub/Sub providers:

nsq for [NSQ](https://nsq.io/)
gcp for [Google Cloud Pub/Sub](https://cloud.google.com/pubsub)
aws for AWS [SNS](https://aws.amazon.com/sns/) + [SQS](https://aws.amazon.com/sqs/)
azure for [Azure Service Bus](https://azure.microsoft.com/en-us/products/service-bus)

https://encore.dev/docs/self-host/configure-infra#9-pubsub-configuration

Is there any plan to support RabbitMQ pub/sub?

Thank you

**Comment by marcuskohlberg** [comment]
Hey Sayyid, answering on here as well for visibility.
We don't have plans to support RabbitMQ in the near term, but you can still use it as you would normally do (without using Encore's framework functions for Pub/Sub).
