### ISSUE TITLE
Trouble recovering from failed 'Provision Infrastructure' step

### ISSUE THREAD

**Issue by jgeden** [encoredev/encore#159]
Hey y'all. First off, I love the project. I've just started working with Go and this framework is a huge bonus for working with the language.

I tried to do my first deploy yesterday and I ran into a few issues. At first it would fail when trying to provision a database.

<img width="805" alt="Screen Shot 2022-03-30 at 12 27 39" src="https://user-images.githubusercontent.com/31145777/160884751-4abab012-042a-4f8b-b5f5-e0f924aa23ca.png">

I waited a few hours and tried again and the database was able to be provisioned, but then the 'Deploy Release' step would fail:
```
BUILD
Pulling image: europe-docker.pkg.dev/encore-prod-deploys/deploy-images/encore-deploy:v0.26.0
v0.26.0: Pulling from encore-prod-deploys/deploy-images/encore-deploy
2df365faf0e3: Already exists
676ef4227e00: Pulling fs layer
622d6bdd21de: Pulling fs layer
676ef4227e00: Verifying Checksum
676ef4227e00: Download complete
676ef4227e00: Pull complete
622d6bdd21de: Verifying Checksum
622d6bdd21de: Download complete
622d6bdd21de: Pull complete
Digest: sha256:46bdd9fb1d04a290171fe3a983508fa81d767fbb72225293fec3a0b91465afbf
Status: Downloaded newer image for europe-docker.pkg.dev/encore-prod-deploys/deploy-images/encore-deploy:v0.26.0
europe-docker.pkg.dev/encore-prod-deploys/deploy-images/encore-deploy:v0.26.0
2022/03/29 18:23:50 migrating database words...
2022/03/29 18:23:51 database words already up to date
2022/03/29 18:23:52 unexpected number of targets: 4
ERROR
ERROR: build step 0 "europe-docker.pkg.dev/encore-prod-deploys/deploy-images/encore-deploy:v0.26.0" failed: step exited with non-zero status: 1
```
 
I think this is because I tried to deploy a few times when the database provision was failing, which resulted in multiple code targets being created.

<img width="652" alt="Screen Shot 2022-03-30 at 12 29 38" src="https://user-images.githubusercontent.com/31145777/160885154-5962787e-a0ae-47e5-b191-b5e657a84d9a.png">

I created a new environment and just selected the same branch to deploy and it was successful that time. This time with only 1 code target.

I haven't looked at any of the source code, so I have no idea what the fix could be, but I would guess that the code target should be removed if the deploy fails on the first deploy.

**Comment by DomBlack** [comment]
Hi @Josh0823, sorry for the late reply; but we're working on a fix for this currently and hope to have it released next week.

**Comment by DomBlack** [comment]
Hi @jgeden; this fix was released a while back - sorry I forgot to update you / close the issue. Please let me know if you're still having issues.
