### ISSUE TITLE
Self-Host Error

### ISSUE THREAD

**Issue by SOG-web** [encoredev/encore#1673]
`encore build docker url-shortener:v1.0
3:06PM INF compiling Encore application for linux/amd64
3:06PM ERR build infra config:
Your infra configuration is incomplete
Missing Resource Configurations:
  Databases: url
`

```json
{
    "$schema": "https://encore.dev/schemas/infra.schema.json",
    "sql_servers": [
       {
          "host": "localhost:5432",
          "databases": {
             "url": {
                "username": "encore-user",
                 "password": {"$env": "DB_PASSWORD"},
                 "max_connections": 100,
                 "min_connections": 10
             }
          }
       }
    ]
 }
 ```
 
 my repo link https://github.com/SOG-web/encore-go-test.git

**Comment by eandre** [comment]
From the CLI command you provided you're not actually passing in the infra config. It needs to be provided using a command-line flag. (On my phone so a bit hard to check what it's named, but it's listed if you add `--help`)

**Comment by SOG-web** [comment]
@eandre thanks it works now, but how do add a port

**Comment by SOG-web** [comment]
> @eandre thanks it works now, but how do add a port

dont worry I found it

**Comment by SOG-web** [comment]
@eandre please lastly is there any dashboard management for self-host in prod, just like we have in dev
