### ISSUE TITLE
Error response

### ISSUE THREAD

**Issue by sopta** [encoredev/encore#17]
Hello,

thanks for this project, it looks very promising. Will be there a possibility to return an error as a JSON? I've tried to write a simple API, but in the case of error, only a text message "Internal server error" is returned. I'd like to specify a structure that holds more information.

**Comment by eandre** [comment]
Hey @sopta, you're absolutely right and I've actually been working on this for the past few days!

I'll publish an RFC most likely tomorrow and an initial implementation to follow not long after that.

**Comment by sopta** [comment]
Awesome! :)
