### ISSUE TITLE
Go client generation

### ISSUE THREAD

**Issue by tomlazar** [encoredev/encore#172]
Encore is awesome first of all, it would be nice, and probably pretty simple to have a go version of the client generation for older legacy version of micro-services, along with things that aren't web servers like CLI's and non-webhook only bots like discord/teams.

**Comment by eandre** [comment]
Hey @tomlazar, thanks very much for the kind words. Those are great points, and we definitely want to add Go client generation.

**Comment by DomBlack** [comment]
Hi @tomlazar; we released Encore v1.0.0 🎉  over the weekend which included support for generating Go Clients. ([example of a generated client](https://github.com/encoredev/encore/blob/main/cli/internal/codegen/testdata/expected_golang.go))

Once you've updated your local CLI you can generate the client for your app with the command;

```bash
encore gen client [your app id] --lang go
```
