### ISSUE TITLE
Running Encore on windows fails

### ISSUE THREAD

**Issue by iw-an** [encoredev/encore#177]
Using the latest install version as provided in the docs, installed via powershell

Creation of the hello world template succeeds correctly and then running `git push encore` runs fine. 

Doing `encore run` fails with:
```
2022/04/20 13:13:35 [ERR] yamux: Failed to read header: read encore-stdin: The handle is invalid.
1:13PM FTL could not listen and serve error="read encore-stdin: The handle is invalid."
```

**Comment by DomBlack** [comment]
Hi @iw-an; we released a new version of Encore over the weekend and included a fix for windows.
