### ISSUE TITLE
Would like the ability to remove environments

### ISSUE THREAD

**Issue by philbenoit** [encoredev/encore#2]
If I have setup an environment I can not currently delete it.

It would be handy to have some delete functionality from the dashboard.

**Comment by eandre** [comment]
Agreed, this is absolutely something we need to support. We have the functionality on the backend, just need to expose it in the frontend.

**Comment by zinderic** [comment]
I wanted to give the framework a test today and I was pretty surprised when my app was deployed to public cloud with no way of removing it from there. It's my fault for not paying enough attention to the docs before I went and run it but now I feel pretty uneasy about using this. It feels unsafe to me.

I come from a background of working with enterprises for many years where privacy and how data is being managed is critical so I might be a bit opinionated about this but feedback is feedback so I decided to mention this here.

**Comment by eandre** [comment]
Hey @zinderic, thanks so much for the feedback. We're adding the ability to remove environments shortly.

Can you share more about your unease? What you're seeing is that Encore sets up a production environment out of the box to make it easy to get started, but Encore only makes public the API endpoints that you define as public. Under no circumstances are your databases made publicly available, and you retain complete control over your data.

**Comment by zinderic** [comment]
When I think about a framework I usually expect to be able to build an enterprise app and keep its code, database and deployment private and controlled.

I might be wrong about that but Encore from my current perspective is closer to a PaaS such as Heroku. It provides great development abstractions to ease a lot of the process of writing apps that can be consumed within a PaaS setup but it's still very much within that space and coupled close to those services.

**Comment by eandre** [comment]
You're right that Encore is a bit different from traditional frameworks. A good way to think about Encore is as a Platform for Software Development – it integrates a larger part of the experience, which is what makes it possible to create a radically improved development experience in the first place. Since you can deploy to your own cloud Encore gives you more flexibility and control over your data than PaaS providers like Heroku.

**Comment by zinderic** [comment]
Yeah, I agree. I think when I saw "backend framework" is when I started placing Encore as something else than a platform-centric experience. It sits between those two abstractions but  the word "framework" carries a lot of baggage that set me in that frame of mind where I didn't expect to get a Platform. But actually the Platform is where the "superpowers" are actually coming from to a great extend, right?

**Comment by eandre** [comment]
Yes, exactly. The pain points with developer productivity don't fit into either "framework" or "infrastructure". Encore bridges the gap between the two, which is exactly why we can provide a much better developer experience and much better productivity :)

I'll note this conversation is quite off-topic from this issue, so in the interest of keeping it on-topic let's move this conversation elsewhere. Feel free to open a discussion, separate issue, or join us on Slack ([encore.dev/slack](https://encore.dev/slack))!

**Comment by eandre** [comment]
Thanks @philbenoit and @zinderic, we've just released support for updating and deleting environments. It's available from the web UI:

![image](https://user-images.githubusercontent.com/425456/125799320-c41aefff-10b8-4188-a195-cac459c7137d.png)
