### ISSUE TITLE
Debugging instructions

### ISSUE THREAD

**Issue by pellared** [encoredev/encore#29]
Is there any option to debug using [`delve`](https://github.com/go-delve/delve)?

Could you describe it, please?

**Comment by eandre** [comment]
You can use `encore run --debug --watch=false` to start the application for debugging. It disables inlining and improves debugging information, and prints the process id that you can use with `dlv attach <pid>`.

**Comment by pellared** [comment]
Maybe worth adding to docs? 😉

**Comment by eandre** [comment]
Great point, will write up a section on it :)
