### ISSUE TITLE
Updating encore doesn't clean the runtime directory

### ISSUE THREAD

**Issue by Minivera** [encoredev/encore#310]
Hi,

I recently updated encore from `0.23.0` to `1.3.1` and, when using `encore run`, it seems like some leftover code from previous versions was causing name conflicts when compiling with the runtime. Here are the errors I was seeing:

```
encore run


  ✔ Building Encore application graph... Done!
  ✔ Analyzing service topology... Done!
  ⠖ Creating PostgreSQL database cluster... 
  ⠦ Generating boilerplate code... 
  ❌ Compiling application source code... Failed: # encore.dev/beta/errs
../../../../../.encore/runtime/beta/errs/internal.go:11:6: Stack redeclared in this block
	../../../../../.encore/runtime/beta/errs/errs_internal.go:33:6: other declaration of Stack
../../../../../.encore/runtime/beta/errs/internal.go:18:6: DropStackFrame redeclared in this block
	../../../../../.encore/runtime/beta/errs/errs_internal.go:40:6: other declaration of DropStackFrame
../../../../../.encore/runtime/beta/errs/internal.go:27:6: RoundTrip redeclared in this block
	../../../../../.encore/runtime/beta/errs/errs_internal.go:49:6: other declaration of RoundTrip

  ⠂ Running database migrations... 
```

After doing some digging, I found that the `internal.go` files [was renamed in April](https://github.com/encoredev/encore/tree/fd16e7c544bda065968db5f8316c08fdfbce232a/runtime/beta/errs) to `errs_internal.go` in the `runtime/beta/errs` directory, and my local installation ended up having both files, which caused conflicts. It would seem the update process does not clear the runtime directory of old files, which may cause issues like this again in the future.

I managed to fix this by deleting the `runtime` directory from `.encore` and reinstalling encore.

**Comment by eandre** [comment]
Thanks @Minivera for the report! The`install.sh` script (available at https://encore.dev/install.sh) contained code to clear out the Go runtime but for some reason I didn't think to also clear out the Encore runtime. I've updated the script to do that, so this should now be fixed for future upgrades. Thanks!

**Comment by Minivera** [comment]
Awesome! Thanks for the quick fix
