### ISSUE TITLE
404 when buttons on pricing is clicked. 

### ISSUE THREAD

**Issue by oseifrimpong** [encoredev/encore#32]
![These buttons](https://user-images.githubusercontent.com/3536601/119067800-6f573d80-ba15-11eb-87aa-c9cdb4b77c26.png)

**Comment by marcuskohlberg** [comment]
Thank you for reporting this!
We'll get right on it.

**Comment by marcuskohlberg** [comment]
Thank you for reporting this!
It's now fixed.
