### ISSUE TITLE
Add Caching Service?

### ISSUE THREAD

**Issue by mrcampbell** [encoredev/encore#363]
I've got an extremely slow external API call and was going to add a caching service in my project, but wondered if there was a general enough definition for a caching service in Encore?

Maybe a wrapper around etcd or Redis?

The service I was envisioning would have Key/Value, TTL and invalidate/delete.  Nothing crazy.

Is this a feature I could contribute to?

**Comment by melkstam** [comment]
I don't work at encore, but they have quite recently added a proposal for caching built around Redis. From my understanding, the proposal should cover your use case. The proposal and discussion can be seen here: https://github.com/encoredev/encore/discussions/355.

**Comment by mrcampbell** [comment]
Perfect!!!  Thank you!!!
