### ISSUE TITLE
Caching: Inconsistent method naming for increment/decrement

### ISSUE THREAD

**Issue by melkstam** [encoredev/encore#378]
The methods for incrementing and decrementing for int and float keyspaces are inconsistent. They are called `Decr` and `Increment`, which I assume is not the intended naming.

- https://pkg.go.dev/encore.dev/storage/cache#FloatKeyspace.Decr
- https://pkg.go.dev/encore.dev/storage/cache#FloatKeyspace.Increment
- https://pkg.go.dev/encore.dev/storage/cache#IntKeyspace.Decr
- https://pkg.go.dev/encore.dev/storage/cache#IntKeyspace.Increment

**Comment by eandre** [comment]
Whoops, great catch. We ended up renaming (or at least we intended to rename) `Incr/Decr` to `Increment/Decrement` at the last minute, but the `Decrement` change got lost. Will fix and issue `v1.7.1` immediately to minimize the issue.
