### ISSUE TITLE
Windows button does not work on encore.dev 

### ISSUE THREAD

**Issue by alfredleo** [encoredev/encore#38]
![image](https://user-images.githubusercontent.com/4072844/120683503-21334700-c4b7-11eb-96a1-29e76a1575ad.png)
I am not sure if this is the right place to report a bug on the encore.dev website. There is a problem with the windows installation button. It works only if we click on the Linux button first. Tested with the latest chrome and firefox browsers.

**Comment by alfredleo** [comment]
Update. I think it looks at what OS I am using and sets commands accordingly. Underline should be set then to the right OS. This confused me a bit. Buttons work just fine, only a problem with the correct underline.

**Comment by marcuskohlberg** [comment]
Thank you for identifying this sneaky bug @alfredleo!
We'll get right on sorting it.

**Comment by marcuskohlberg** [comment]
This is now fixed. Thanks again @alfredleo!
