### ISSUE TITLE
Docs(Caching): Link to wrong keyspace on pkg.go.dev

### ISSUE THREAD

**Issue by melkstam** [encoredev/encore#381]
In the caching documentation, the link to the struct keyspace docs on pkg.go.dev actually points to the string keyspace docs.

https://github.com/encoredev/encore/blob/43a88f083d3c32c7773eddea49c457d3982514f5/docs/develop/caching.md?plain=1#L150

**Comment by eandre** [comment]
This is fixed in v1.7.1, thanks!
