### ISSUE TITLE
Encore failing to deploy infrastrustrure 

### ISSUE THREAD

**Issue by phippsy22** [encoredev/encore#40]
Hello,

**Issue**: I've created a basic application and I'm running into the below error message when deploying to prod:

```
remote:  05:40 |  infra | Failed to configure infrastructure: cloud.Encore.Configure: failed to run op *k8s.ingressCreator: clusterroles.rbac.authorization.k8s.io "external-ingress" is forbidden: user "system:serviceaccount:default:encore-deploy" (groups=["system:serviceaccounts" "system:serviceaccounts:default" "system:authenticated"]) is attempting to grant RBAC permissions not currently held:
remote: {APIGroups:["extensions"], Resources:["ingressclasses"], Verbs:["get" "list" "watch"]}
remote: {APIGroups:["networking.k8s.io"], Resources:["ingressclasses"], Verbs:["get" "list" "watch"]}
```

Additionally I created a dev branch and attempted to deploy the same code as an attempt to replicate and ran into the same issue.

**Full prod deploy log**: https://gist.github.com/phippsy22/709da31bf3d53c54a4d229ed337ddade
**Full dev deploy log**: https://gist.github.com/phippsy22/ba3b8ffb696c69c454805667691e0a8f

**Note**
- I am a noobie with encore so I am not sure if I have missed anything. However I was not able to find any information on defining infrastructure.

**Version**:
```
encore version v0.14.5
```

**Comment by eandre** [comment]
Hey @phippsy22, thanks for the report! There was nothing you did on your end; it was a regression on our end. I've fixed the issue and retriggered your deploy so your app is up and running now.
