### ISSUE TITLE
Docs: Difference in the content of docs/quick-start on the website and on this repository

### ISSUE THREAD

**Issue by kVarunkk** [encoredev/encore#419]
There is a noticeable difference in the content of docs/quick-start on the [encore website](https://encore.dev/docs/quick-start) and on the  [quick-start.md](https://github.com/encoredev/encore/blob/main/docs/quick-start.md) found in this repository.

Differences:

- **Run your app locally** and **Explore Encore** are 2 different headings in the website and repo respectively with the same content underneath them
-  The heading **Update your test** and its content is only found in the repo and is missing from the website.

Thanks!

**Comment by marcuskohlberg** [comment]
Thanks @kVarunkk, this has been fixed!
