### ISSUE TITLE
Adding Issue Template

### ISSUE THREAD

**Issue by Smartmind12** [encoredev/encore#443]
Currently there are no templates for users to Create Issues. Hence adding Templates would streamline the process of raising an issue in the repository or contributing to the same.

Kindly assign this issue to me so that I can start working on it ...Thanks!

**Comment by pwnb0y** [comment]
assign me

**Comment by Smartmind12** [comment]
> assign me

I raised this issue and i am waiting for it to be assigned to me …kindly find another issue …Thanks!!
