### ISSUE TITLE
Adding Pull Request Template

### ISSUE THREAD

**Issue by Smartmind12** [encoredev/encore#444]
Currently there is absence of the Pull request template which results into unstructured pull requests, making it difficult for admins to review and users to checkout these PR. Hence would suggest addition of Pull Request template to make such contributions streamlined and structured.

Kindly assign this issue to me so that I can contribute to this...Thanks!

**Comment by pwnb0y** [comment]
assign me

**Comment by Smartmind12** [comment]
> assign me

I raised this issue and i am waiting for it to be assigned to me …kindly find another issue …Thanks!!
