### ISSUE TITLE
Add support for PostgreSQL extensions (e.g., PostGIS, TimescaleDB)

### ISSUE THREAD

**Issue by pablojimpas** [encoredev/encore#461]
Hi!

I've just discovered Encore, and I'm planning to use it for a project that will rely on some PostgreSQL extensions.
Is this possible already today? I didn't find anything in the docs and I assumed that being an opinionated solution you provision a pre-configured Docker container with the database and there is no way to customize this deployment. Hopefully I'm wrong and this is already possible, otherwise consider this as a feature request.

**Comment by marcuskohlberg** [comment]
Hey @pablojimpas, sorry for missing your questions.
Here's documentation for the supported extensions: https://encore.dev/docs/primitives/databases/extensions

If there are any missing ones you need in your application, please submit an issue. :)
