### ISSUE TITLE
Encore daemon doesn't detect restarted database container

### ISSUE THREAD

**Issue by eandre** [encoredev/encore#49]
The Encore daemon caches information about the running database container. This works fine most of the time but causes problems when the Docker container (or Docker itself) is restarted outside of Encore's control, leading to Encore trying to connect to the wrong (ephemeral) container port.

It leads to errors like:
```
error: could not connect to the database for service foo/: create db mapping: failed to connect to admin database: failed to connect to `host=0.0.0.0 user=encore database=postgres`: dial error (dial tcp 0.0.0.0:49153: connect: connection refused)
```

A workaround is to restart the encore daemon (by running `encore daemon`) to clear the cache, but the daemon should detect this by itself instead.

**Comment by scastrec** [comment]
Thanks to this, It solve this error too:
`  ❌ Running database migrations... Failed: create db notes: failed to connect to admin database: failed to connect to `host=0.0.0.0 user=encore database=postgres`: dial error (dial tcp 0.0.0.0:61483: connect: connection refused)`

**Comment by eandre** [comment]
Yes, the bugfix in #113 should fix that. Before we tag a new release with that bugfix you can work around the issue by running `encore daemon` from your terminal to restart the daemon (which clears the cache). Hope that helps :)
