### ISSUE TITLE
XSS in cli/daemon

### ISSUE THREAD

**Issue by jfcg** [encoredev/encore#5]
https://github.com/encoredev/encore/blob/1df6e06e67d300d5053e6559759338232af405aa/cli/daemon/runtime/runtime.go#L38-L51

Cross-site scripting vulnerability due to unsanitized pid header. Reported by Github CodeQL. See Security -> Code Scanning Alerts

**Comment by eandre** [comment]
Thanks for your report. This seems like a false positive to me. The client in this case is not a browser, and this is only running as a local webserver. But happy to change it so that it's not detected as a false positive of course.

**Comment by eandre** [comment]
Closing because this is a false positive. Please reopen if you believe otherwise. Thanks!
