### ISSUE TITLE
Dashboard not providing most recent request result.

### ISSUE THREAD

**Issue by MaxDanielsson** [encoredev/encore#53]
If a request to an API is successful and the next fails, the Encore gui sometimes still show the most recent success instead of error.
![Screenshot from 2021-08-11 10-45-56](https://user-images.githubusercontent.com/33028551/128999304-e7d5e196-256d-4014-abf8-5b26e24f47d2.png)

**Comment by eandre** [comment]
Thanks @MaxDanielsson! Just to clarify, you mean the left-hand side showing the response does not update in that case?

**Comment by MaxDanielsson** [comment]
Yes! 
It instead shows the most recent success.
