### ISSUE TITLE
`encore run` output control codes shown in Windows

### ISSUE THREAD

**Issue by kravlost** [encoredev/encore#56]
After I start `encore run`, the formatting control codes are shown in Windows:

`←[90m8:35PM←[0m ←[32mINF←[0m registered endpoint ←[36mendpoint=←[0mWorld ←[36mpath=←[0m/hello.World ←[36mservice=←[0mhello`

**Comment by eandre** [comment]
Thanks for the report, that's interesting. Which terminal did you use? I'm guessing that Windows Terminal should support this? (Needs a fix regardless but just as a temporary workaround)

**Comment by frzam** [comment]
@kravlost Can you please let us know which terminal you are using and windows version? 

I have tried to replicate the scenario, so on *windows command prompt* and *powershell* it is working properly, but on git bash it is printing color code junk.
**cmd prompt output:**
<img width="649" alt="cmd-prompt" src="https://user-images.githubusercontent.com/22986964/129437690-d7eabfbc-80f6-4125-a4e9-558140b65f6f.PNG">
**git bash output**
<img width="596" alt="bash" src="https://user-images.githubusercontent.com/22986964/129437707-4764314e-d9b7-4043-b2d1-33931175998c.PNG">

@eandre  so if you want to give support for git bash as well then we can enable `ENABLE_VIRTUAL_TERMINAL_PROCESSING` for **windows** in `main()`
```go
	if runtime.GOOS == "windows" {
		console := windows.Handle(os.Stdout.Fd())
		var originalMode uint32
		windows.GetConsoleMode(console, &originalMode)
		windows.SetConsoleMode(console, originalMode|windows.ENABLE_VIRTUAL_TERMINAL_PROCESSING)
	}
```
This is resolving issue in windows git bash as well. Let me know your thoughts.

**Comment by kravlost** [comment]
@frzam @eandre Thanks for the replies. Here's my info:

Windows version:

Edition	Windows 10 Home
Version	21H1
OS build	19043.1165
Experience	Windows Feature Experience Pack 120.2212.3530.0
(UK English experience pack)

Powershell version:
Powershell 64-bit 7.1.4.

I also get the same result in cmd.exe.

**Comment by kravlost** [comment]
@frzam @eandre An update! According to [this](https://stackoverflow.com/questions/51680709/colored-text-output-in-powershell-console-using-ansi-vt100-codes) answer, PS doesn't support ANSI escape sequences out of the box. If I pipe Encore's output through Out-Host as suggested in answer 3, it works fine:

![image](https://user-images.githubusercontent.com/4245329/129441373-0bc66b5d-8a9e-4e5f-91d5-fabafb331384.png)

**Comment by eandre** [comment]
Thanks @frzam and @kravlost for investigating! Based on the StackOverflow answer it seems like @frzam's solution with changing the console mode should work. I think we should do it for both `stdout` and `stderr`. Either of you want to send a PR? :)

**Comment by frzam** [comment]
Yup I will pull request.
