### ISSUE TITLE
[DOCS/CLI] Generating client fails due to wrong information

### ISSUE THREAD

**Issue by randallmlough** [encoredev/encore#6]
Tried to generate a client based off your Trello Clone example (unedited, kept as is) and it kept erroring out. I read the docs and even the cli help command. Docs and CLI say to use "ts" but when actually looking at the source code, "typescript" is the correct value instead of "ts"

**Comment by eandre** [comment]
Thanks @randallmlough, you're absolutely right! I've just pushed a fix to the `encore gen client --help` docs, and also updated the encore.dev/docs site to match.
