### ISSUE TITLE
[BUG]: Topic missing publisher role in GCP deployment

### ISSUE THREAD

**Issue by onlywicked** [encoredev/encore#652]
## Description

Few days back, I faced an issue when I deployed my application to GCP for production usage.
The `topic` created was missing publisher role for the Cloud Run.

<img width="410" alt="Screenshot 2023-04-04 at 4 23 52 PM" src="https://user-images.githubusercontent.com/17452272/229771127-34403b6f-4313-4116-a837-8b9e9fd5fe4e.png">

---
To fix it I have to manually add the permission.

**Comment by eandre** [comment]
Hi @onlywicked, thanks for the report. Did you actually call `Publish` on the topic somewhere? Encore only adds the permission when you actually publish messages.

**Comment by onlywicked** [comment]
@eandre Yep, I did.
Because and that's how I came to know about it.

I was getting the following error:

`failed to publish message to {topic_name}: rpc error: code = PermissionDenied desc = User not authorized to perform this action.`

After that I went into project and found that the permission wasn't there.

**Comment by eandre** [comment]
Hmm, that's very strange, that shouldn't happen. Can you share which Encore application and which deploy id that triggered this? I'll have a look at the infrastructure planning.

**Comment by onlywicked** [comment]
Sure. Sent it to you slack.

**Comment by eandre** [comment]
This has been fixed with the latest release, thank you!
