### ISSUE TITLE
Proposal: improved database support

### ISSUE THREAD

**Issue by eandre** [encoredev/encore#67]
# Proposal: Improved database support
## Summary
We propose several improvements to Encore’s SQL Database functionality, in order to improve flexibility by (1) supporting the use of ORMs and other libraries that rely on wrapping a `*database/sql.DB`, and (2) enabling multiple services to refer to the same database.

## Motivation
Encore improves on several aspects relating to using SQL databases, such as provisioning and configuration, schema migrations, and easily connecting to and querying databases with minimal boilerplate necessary.

Encore currently provides package-global functions (such as `encore.dev/storage/sqldb.Query`) that leverage static analysis to automatically infer which service is calling them (and therefore which database to connect to, as we currently map databases one-to-one to services). This design has unfortunately proven to be too limiting.

The main limitation is that Encore requires all calls to `sqldb` functions to be made within a service, so that Encore can map them at compile-time to the relevant database. This prevents the use of reusable utility libraries and ORMs. It also makes it impossible to support multiple services referencing the same database or connecting to an external database. By lifting this limitation we’ll add a great deal of additional flexibility in how people can use Encore’s database support.

## Detailed Design
There are two main challenges to consider:

1. Mapping queries to the appropriate database
2. Tracing database queries

For the first part, we propose to add the concept of *Named Databases*. This means that instead of mapping implicitly to “the current service’s database”, Encore will provide (in the `encore.dev/storage/sqldb` package) a function that provides a database object given a name:

```go
// Named returns a database object for the db with the given name.
// The name must be provided as a constant string in order to facilitate
// compile-time checking and static analysis.
func Named(dbName string) *sqldb.Database { /* ... */ } 

// Stdlib returns a *sql.DB object that is connected to the same db,
// for use with libraries that expect a *sql.DB.
func (*sqldb.Database) Stdlib() *sql.DB
```

As noted in the documentation comment, the `*sqldb.Database` object returned can only be assigned to an unexported variable

Each Encore-provisioned database will have a name equal to the service it is created within. If other services (or packages outside the service that “owns” the database) want to access the same database, they can all refer to it by the service name:

```go
package dbhelpers

var db = sqldb.Named("someservice")

func ListFoos(ctx context.Context) ([]*Foo, error) {
	rows, err := db.Query(ctx, "...")
	// ...
}
```

For backwards compatibility Encore will of course continue to provide the existing package-level `sqldb.Query` (etc.) functions that map to the current service’s database.

### Tracing database queries
In order to continue automatically trace database queries the database object returned by `sqldb.Named` will use a custom driver that wraps the underlying database driver (in Encore’s case [github.com/jackc/pgx](https://github.com/jackc/pgx)), based on the approach taken by [github.com/ngrok/sqlmw](https://github.com/ngrok/sqlmw). 

### Downsides
The main downside to this approach is that when a developer writes a query statement (`db.Query(ctx, "foo")`) we can't in the general case know which database is being queried. This limits our ability to improve the user experience through code intelligence, query auto-completion, static analysis, and so on.

The best way to combat these limitations is through being clear about best practices: 

* Avoid passing around `*sqldb.Database` objects between functions; use a package-level variable instead.
* Use a `*sqldb.Database` when possible over the standard library version

## Future work
This proposal is designed with the intent of supporting connecting to external databases. The idea is that an external database will be given a name, just like an Encore-provisioned database, that can then be connected to with `sqldb.Named("name")`. That is not in scope for this proposal but is a planned extension of this work.

**Comment by mvp-joe** [comment]
I like this idea a lot.  It would be super helpful to be able to use third-party go SQL ORMs & mappers - honestly one of the biggest pain points with encore right now.

Thanks for the proposal @eandre!

**Comment by windwp** [comment]
@eandre 
hi is there any example of how to you encore with gorm. 
sorry, i am new to golang I am comming from nodejs .just learn go a bit. 
I need a way to get connect string from encore then I can use gorm.
Thank
