### ISSUE TITLE
Document how to handle dirty database migrations

### ISSUE THREAD

**Issue by eandre** [encoredev/encore#68]
When a database migration doesn't apply cleanly, `golang-migrate` (the library we use under the hood to manage database migrations) marks the migration state as "dirty" and refuses to continue. This can be fixed by editing the database table (fixing the schema problem and then running `UPDATE schema_migrations SET dirty = false`), but that's not documented anywhere. We should add this to [SQL Database documentation](https://github.com/encoredev/encore/blob/main/docs/develop/databases.md).

**Comment by wisdommatt** [comment]
@eandre assign this issue to me, i would like to work on adding this to encore SQL database documentation.

**Comment by eandre** [comment]
Sounds great, thank you!
