### ISSUE TITLE
Fatal error when running in debug mode

### ISSUE THREAD

**Issue by peakstack** [encoredev/encore#704]
Hi, 
i was running my application in debug mode and called the url with curl: curl http://localhost:4000/url -d '{"URL":"hello"}'
I am using the url shortener template. The application just stopped, so I am not able to debug my application. I did not even have the debugger attached.
I am running 6.3.0-1-MANJARO.
Running it with "encore run" works fine.

**LOG:**
✔ Building Encore application graph... Done!
  ✔ Analyzing service topology... Done!
  ✔ Building Encore application graph... Done!
  ✔ Analyzing service topology... Done!
  ✔ Creating PostgreSQL database cluster... Done!
  ✔ Generating boilerplate code... Done!
  ✔ Compiling application source code... Done!
  ✔ Pulling PostgreSQL docker image... Done!
  ✔ Running database migrations... Done!
  ✔ Starting Encore application... Done!

  Encore development server running!

  Your API is running at:     http://localhost:4000
  Development Dashboard URL:  http://localhost:9400/xxxxxxxxxxxxxxxx
  Process ID:             7583

4:01PM INF registered API endpoint endpoint=Shorten path=/url service=url
4:01PM INF registered API endpoint endpoint=Get path=/url/:id service=url
4:01PM INF listening for incoming HTTP requests

Hint: make an API call by running: curl http://localhost:4000/url -d '{"URL":"hello"}'
4:01PM INF starting request endpoint=Shorten service=url trace_id=xxxxxxxxxxxxxx
fatal error: defer on system stack

runtime stack:
runtime.throw({0x122d671?, 0xc000390020?})
        /home/canary/.encore/encore-go/src/runtime/panic.go:1047 +0x5d fp=0x7f51af7fdb78 sp=0x7f51af7fdb48 pc=0x44b05d
runtime.deferprocStack(0x203000?)
        /home/canary/.encore/encore-go/src/runtime/panic.go:311 +0x87 fp=0x7f51af7fdb98 sp=0x7f51af7fdb78 pc=0x4495e7
encore.dev/appruntime/exported/trace.(*Log).Add(0xc000390020, 0x3, {0x7f51af7fdd34, 0xc, 0xc})
        /home/canary/.encore/runtime/appruntime/exported/trace/log.go:36 +0x115 fp=0x7f51af7fdd08 sp=0x7f51af7fdb98 pc=0xa4bfd5
encore.dev/appruntime/exported/trace.(*Log).GoStart(0xc000390020, {0x3, 0xbe, 0x85, 0x74, 0xca, 0x5f, 0xa2, 0x6d}, 0x3)
        /home/canary/.encore/runtime/appruntime/exported/trace/events.go:337 +0x145 fp=0x7f51af7fdd70 sp=0x7f51af7fdd08 pc=0xa48425
runtime.startEncoreG(0xc000384048)
        /home/canary/.encore/runtime/appruntime/shared/reqtrack/impl_app.go:55 +0x14b fp=0x7f51af7fddc8 sp=0x7f51af7fdd70 pc=0xa5374b
runtime.newproc1(0xc000390100, 0xc000392000, 0xd86eb8)
        /home/canary/.encore/encore-go/src/runtime/proc.go:4306 +0x192 fp=0x7f51af7fde20 sp=0x7f51af7fddc8 pc=0x455d12
runtime.newproc.func1()
        /home/canary/.encore/encore-go/src/runtime/proc.go:4250 +0x25 fp=0x7f51af7fde50 sp=0x7f51af7fde20 pc=0x455b25
runtime.systemstack()
        /home/canary/.encore/encore-go/src/runtime/asm_amd64.s:496 +0x49 fp=0x7f51af7fde58 sp=0x7f51af7fde50 pc=0x47df69

goroutine 50 [running]:
runtime.systemstack_switch()
        /home/canary/.encore/encore-go/src/runtime/asm_amd64.s:463 fp=0xc0003d9c70 sp=0xc0003d9c68 pc=0x47df00
runtime.newproc(0x12b4c20?)
        /home/canary/.encore/encore-go/src/runtime/proc.go:4249 +0x51 fp=0xc0003d9ca8 sp=0xc0003d9c70 pc=0x455ad1
github.com/jackc/pgx/v5/pgxpool.NewWithConfig({0x12bf0b0, 0xc000122000}, 0xc0003822a0)
        /home/canary/go/pkg/mod/github.com/jackc/pgx/v5@v5.3.1/pgxpool/pool.go:253 +0x558 fp=0xc0003d9d70 sp=0xc0003d9ca8 pc=0xd86eb8
encore.dev/storage/sqldb.(*Manager).getPool(0xc00013c410, {0x12238a0, 0x3})
        /home/canary/.encore/runtime/storage/sqldb/manager_internal.go:94 +0x2d0 fp=0xc0003d9ee8 sp=0xc0003d9d70 pc=0xd9faf0
encore.dev/storage/sqldb.(*Manager).GetDB(0xc00013c410, {0x12238a0, 0x3})
        /home/canary/.encore/runtime/storage/sqldb/manager_internal.go:67 +0x297 fp=0xc0003da010 sp=0xc0003d9ee8 pc=0xd9f5d7
encore.dev/storage/sqldb.(*Manager).GetCurrentDB(0xc00013c410)
        /home/canary/.encore/runtime/storage/sqldb/manager_internal.go:47 +0xcd fp=0xc0003da098 sp=0xc0003da010 pc=0xd9f2ed
encore.dev/storage/sqldb.getCurrentDB()
        /home/canary/.encore/runtime/storage/sqldb/pkgfn.go:128 +0x29 fp=0xc0003da0c0 sp=0xc0003da098 pc=0xda0b09
encore.dev/storage/sqldb.Exec({0x12bf120, 0xc00038e150}, {0x12463bc, 0x39}, {0xc0003900a0, 0x2, 0x2})
        /home/canary/.encore/runtime/storage/sqldb/pkgfn.go:47 +0x6f fp=0xc0003da178 sp=0xc0003da0c0 pc=0xda088f
encore.app/url.insert({0x12bf120, 0xc00038e150}, {0xc0003a8180, 0x8}, {0xc0003a80c8, 0x5})
        /home/canary/GolandProjects/example-app/url/url.go:56 +0x167 fp=0xc0003da250 sp=0xc0003da178 pc=0xdb24c7
encore.app/url.Shorten({0x12bf120, 0xc00038e150}, 0xc00039c0b0)
        /home/canary/GolandProjects/example-app/url/url.go:27 +0x174 fp=0xc0003da330 sp=0xc0003da250 pc=0xdb1dd4
encore.app/url.glob..func1({0x12bf120, 0xc00038e150}, 0xc000388008)
        /home/canary/GolandProjects/example-app/url/encore_internal__api.go:28 +0x85 fp=0xc0003da3c0 sp=0xc0003da330 pc=0xdafe05
encore.dev/appruntime/apisdk/api.(*Desc[...]).invokeHandlerNonRaw(0x12d3ca0, {{0x12bf120, 0xc00038e150}, 0xc000390080}, 0xc000388008)
        /home/canary/.encore/runtime/appruntime/apisdk/api/handler.go:314 +0xe5 fp=0xc0003da480 sp=0xc0003da3c0 pc=0xdb64c5
encore.dev/appruntime/apisdk/api.(*Desc[...]).handleIncoming.func1()
        /home/canary/.encore/runtime/appruntime/apisdk/api/handler.go:212 +0x268 fp=0xc0003da618 sp=0xc0003da480 pc=0xdb48c8
encore.dev/appruntime/apisdk/api.(*Desc[...]).executeEndpoint.func1()
        /home/canary/.encore/runtime/appruntime/apisdk/api/handler.go:279 +0x494 fp=0xc0003da8e8 sp=0xc0003da618 pc=0xdb3d94
encore.dev/appruntime/apisdk/api.(*Desc[...]).executeEndpoint(0x12d3ca0, {0xc00016e280, {0x12bf120, 0xc00038e150}, {0x18309c8, 0x0, 0x0}, {0x23, 0x76, 0xa1, ...}, ...}, ...)
        /home/canary/.encore/runtime/appruntime/apisdk/api/handler.go:293 +0x407 fp=0xc0003dab10 sp=0xc0003da8e8 pc=0xdb6a67
encore.dev/appruntime/apisdk/api.(*Desc[...]).handleIncoming(0x12d3ca0, {{0xc00016e280, {0x12bf120, 0xc00038e150}, {0x18309c8, 0x0, 0x0}, {0x23, 0x76, 0xa1, ...}, ...}, ...}, ...)
        /home/canary/.encore/runtime/appruntime/apisdk/api/handler.go:216 +0x2b8 fp=0xc0003dac60 sp=0xc0003dab10 pc=0xdb7138
encore.dev/appruntime/apisdk/api.(*Desc[...]).Handle(0x12d3ca0, {{0xc00016e280, {0x12bf120, 0xc00038e150}, {0x18309c8, 0x0, 0x0}, {0x23, 0x76, 0xa1, ...}, ...}, ...})
        /home/canary/.encore/runtime/appruntime/apisdk/api/handler.go:116 +0x285 fp=0xc0003dae28 sp=0xc0003dac60 pc=0xdb83a5
encore.dev/appruntime/apisdk/api.(*Desc[...]).Handle({{0xc00016e280, {0x12bf120, 0xc00038e150}, {0x18309c8, 0x0, 0x0}, {0x23, 0x76, 0xa1, 0xde, ...}, ...}, ...})
        /home/canary/.encore/runtime/appruntime/apisdk/api/handler.go:103 +0x5f fp=0xc0003daec8 sp=0xc0003dae28 pc=0xdb927f
encore.dev/appruntime/apisdk/api.(*Server).processRequest(0xc00016e280, {0x12c1cc8, 0x1796fe0}, {{0xc00016e280, {0x12bf120, 0xc00038e150}, {0x18309c8, 0x0, 0x0}, {0x23, ...}, ...}, ...})
        /home/canary/.encore/runtime/appruntime/apisdk/api/server.go:357 +0x25c fp=0xc0003db040 sp=0xc0003daec8 pc=0xaca03c
encore.dev/appruntime/apisdk/api.(*Server).registerEndpoint.func1({0x12be4a0, 0xc0003bc000}, 0xc0003ac100, {0x0, 0x0, 0x0})
        /home/canary/.encore/runtime/appruntime/apisdk/api/server.go:221 +0x4b8 fp=0xc0003db2c8 sp=0xc0003db040 pc=0xac8d58
encore.dev/appruntime/apisdk/api.(*Server).handler(0xc00016e280, {0x12be4a0, 0xc0003bc000}, 0xc0003ac100)
        /home/canary/.encore/runtime/appruntime/apisdk/api/server.go:342 +0x68d fp=0xc0003db488 sp=0xc0003db2c8 pc=0xac99ad
encore.dev/appruntime/apisdk/api.(*Server).handler-fm({0x12be4a0, 0xc0003bc000}, 0xc0003ac000)
        <autogenerated>:1 +0x49 fp=0xc0003db4c0 sp=0xc0003db488 pc=0xacdbc9
net/http.HandlerFunc.ServeHTTP(0xc00017fd70, {0x12be4a0, 0xc0003bc000}, 0xc0003ac000)
        /home/canary/.encore/encore-go/src/net/http/server.go:2122 +0x43 fp=0xc0003db4e8 sp=0xc0003db4c0 pc=0x8bdba3
github.com/rs/cors.(*Cors).Handler.func1({0x12be4a0, 0xc0003bc000}, 0xc0003ac000)
        /home/canary/go/pkg/mod/github.com/rs/cors@v1.8.3-0.20221003140808-fcebdb403f4d/cors.go:236 +0x306 fp=0xc0003db568 sp=0xc0003db4e8 pc=0xa579c6
net/http.HandlerFunc.ServeHTTP(0xc00013a9a0, {0x12be4a0, 0xc0003bc000}, 0xc0003ac000)
        /home/canary/.encore/encore-go/src/net/http/server.go:2122 +0x43 fp=0xc0003db590 sp=0xc0003db568 pc=0x8bdba3
net/http.serverHandler.ServeHTTP({0xc0001c8000}, {0x12be4a0, 0xc0003bc000}, 0xc0003ac000)
        /home/canary/.encore/encore-go/src/net/http/server.go:2936 +0x494 fp=0xc0003db698 sp=0xc0003db590 pc=0x8c2894
net/http.(*conn).serve(0xc00038c000, {0x12bf078, 0xc0003860a0})
        /home/canary/.encore/encore-go/src/net/http/server.go:1995 +0x19b5 fp=0xc0003dbfa0 sp=0xc0003db698 pc=0x8bc875
net/http.(*Server).Serve.func3()
        /home/canary/.encore/encore-go/src/net/http/server.go:3089 +0x45 fp=0xc0003dbfe0 sp=0xc0003dbfa0 pc=0x8c3765
runtime.goexit()
        /home/canary/.encore/encore-go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0003dbfe8 sp=0xc0003dbfe0 pc=0x480121
created by net/http.(*Server).Serve
        /home/canary/.encore/encore-go/src/net/http/server.go:3089 +0xa16

goroutine 1 [select]:
runtime.gopark(0x126bce8, 0x0, 0x9, 0x18, 0x1)
        /home/canary/.encore/encore-go/src/runtime/proc.go:381 +0xfd fp=0xc0001a56d8 sp=0xc0001a56a8 pc=0x44dc5d
runtime.selectgo(0xc0001a58d0, 0xc0001a5868, 0xa?, 0x0, 0xc0001a5950?, 0x1)
        /home/canary/.encore/encore-go/src/runtime/select.go:327 +0xa4a fp=0xc0001a5830 sp=0xc0001a56d8 pc=0x45e02a
github.com/hashicorp/yamux.(*Session).AcceptStream(0xc0001c4180)
        /home/canary/go/pkg/mod/github.com/hashicorp/yamux@v0.1.1/session.go:242 +0xdb fp=0xc0001a5900 sp=0xc0001a5830 pc=0xf7fa7b
github.com/hashicorp/yamux.(*Session).Accept(0xc0001c4180)
        /home/canary/go/pkg/mod/github.com/hashicorp/yamux@v0.1.1/session.go:232 +0x48 fp=0xc0001a5980 sp=0xc0001a5900 pc=0xf7f8c8
net/http.(*onceCloseListener).Accept(0xc0001cb020)
        <autogenerated>:1 +0x5c fp=0xc0001a59f8 sp=0xc0001a5980 pc=0x8fbcdc
net/http.(*Server).Serve(0xc0001c8000, {0x12bd840, 0xc0001c4180})
        /home/canary/.encore/encore-go/src/net/http/server.go:3059 +0x4d0 fp=0xc0001a5cf0 sp=0xc0001a59f8 pc=0x8c3170
encore.dev/appruntime/apisdk/api.(*Server).Serve(0xc00016e280, {0x12bd840, 0xc0001c4180})
        /home/canary/.encore/runtime/appruntime/apisdk/api/server.go:267 +0x7d fp=0xc0001a5d50 sp=0xc0001a5cf0 pc=0xac923d
encore.dev/appruntime/apisdk/app.(*App).Run(0xc0001b4b80)
        /home/canary/.encore/runtime/appruntime/apisdk/app/app.go:48 +0x28d fp=0xc0001a5eb0 sp=0xc0001a5d50 pc=0xf88fed
encore.dev/appruntime/apisdk/app/appinit.AppMain()
        /home/canary/.encore/runtime/appruntime/apisdk/app/appinit/appinit.go:19 +0x74 fp=0xc0001a5f70 sp=0xc0001a5eb0 pc=0xf8a034
main.main()
        /home/canary/GolandProjects/example-app/__encore/main/main.go:9 +0x17 fp=0xc0001a5f80 sp=0xc0001a5f70 pc=0xf8a137
runtime.main()
        /home/canary/.encore/encore-go/src/runtime/proc.go:250 +0x1d3 fp=0xc0001a5fe0 sp=0xc0001a5f80 pc=0x44d7b3
runtime.goexit()
        /home/canary/.encore/encore-go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0001a5fe8 sp=0xc0001a5fe0 pc=0x480121

goroutine 2 [force gc (idle)]:
runtime.gopark(0x126bc80, 0x18006d0, 0x11, 0x14, 0x1)
        /home/canary/.encore/encore-go/src/runtime/proc.go:381 +0xfd fp=0xc000076f88 sp=0xc000076f58 pc=0x44dc5d
runtime.goparkunlock(0x0?, 0x0?, 0x0?, 0x0?)
        /home/canary/.encore/encore-go/src/runtime/proc.go:387 +0x2a fp=0xc000076fb8 sp=0xc000076f88 pc=0x44dcea
runtime.forcegchelper()
        /home/canary/.encore/encore-go/src/runtime/proc.go:305 +0xb0 fp=0xc000076fe0 sp=0xc000076fb8 pc=0x44da30
runtime.goexit()
        /home/canary/.encore/encore-go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000076fe8 sp=0xc000076fe0 pc=0x480121
created by runtime.init.6
        /home/canary/.encore/encore-go/src/runtime/proc.go:293 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x126bc80, 0x1800f00, 0xc, 0x14, 0x1)
        /home/canary/.encore/encore-go/src/runtime/proc.go:381 +0xfd fp=0xc000077758 sp=0xc000077728 pc=0x44dc5d
runtime.goparkunlock(0x0?, 0x0?, 0x0?, 0x0?)
        /home/canary/.encore/encore-go/src/runtime/proc.go:387 +0x2a fp=0xc000077788 sp=0xc000077758 pc=0x44dcea
runtime.bgsweep(0x0?)
        /home/canary/.encore/encore-go/src/runtime/mgcsweep.go:278 +0x98 fp=0xc0000777c8 sp=0xc000077788 pc=0x436c38
runtime.gcenable.func1()
        /home/canary/.encore/encore-go/src/runtime/mgc.go:178 +0x26 fp=0xc0000777e0 sp=0xc0000777c8 pc=0x42b026
runtime.goexit()
        /home/canary/.encore/encore-go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000777e8 sp=0xc0000777e0 pc=0x480121
created by runtime.gcenable
        /home/canary/.encore/encore-go/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x126bc80, 0x18016c0, 0xd, 0x14, 0x2)
        /home/canary/.encore/encore-go/src/runtime/proc.go:381 +0xfd fp=0xc000077f48 sp=0xc000077f18 pc=0x44dc5d
runtime.goparkunlock(0x12b03b8?, 0x1?, 0x0?, 0x0?)
        /home/canary/.encore/encore-go/src/runtime/proc.go:387 +0x2a fp=0xc000077f78 sp=0xc000077f48 pc=0x44dcea
runtime.(*scavengerState).park(0x18016c0)
        /home/canary/.encore/encore-go/src/runtime/mgcscavenge.go:400 +0x4b fp=0xc000077fa0 sp=0xc000077f78 pc=0x4346eb
runtime.bgscavenge(0x0?)
        /home/canary/.encore/encore-go/src/runtime/mgcscavenge.go:628 +0x45 fp=0xc000077fc8 sp=0xc000077fa0 pc=0x434cc5
runtime.gcenable.func2()
        /home/canary/.encore/encore-go/src/runtime/mgc.go:179 +0x26 fp=0xc000077fe0 sp=0xc000077fc8 pc=0x42afc6
runtime.goexit()
        /home/canary/.encore/encore-go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000077fe8 sp=0xc000077fe0 pc=0x480121
created by runtime.gcenable
        /home/canary/.encore/encore-go/src/runtime/mgc.go:179 +0xaa

goroutine 18 [finalizer wait]:
runtime.gopark(0x126b988, 0x18308d0, 0x10, 0x14, 0x1)
        /home/canary/.encore/encore-go/src/runtime/proc.go:381 +0xfd fp=0xc000076628 sp=0xc0000765f8 pc=0x44dc5d
runtime.runfinq()
        /home/canary/.encore/encore-go/src/runtime/mfinal.go:193 +0x107 fp=0xc0000767e0 sp=0xc000076628 pc=0x42a087
runtime.goexit()
        /home/canary/.encore/encore-go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000767e8 sp=0xc0000767e0 pc=0x480121
created by runtime.createfing
        /home/canary/.encore/encore-go/src/runtime/mfinal.go:163 +0x50

goroutine 19 [select, locked to thread]:
runtime.gopark(0x126bce8, 0x0, 0x9, 0x18, 0x1)
        /home/canary/.encore/encore-go/src/runtime/proc.go:381 +0xfd fp=0xc0000725f8 sp=0xc0000725c8 pc=0x44dc5d
runtime.selectgo(0xc0000727a8, 0xc0000727a0, 0x0?, 0x0, 0x0?, 0x1)
        /home/canary/.encore/encore-go/src/runtime/select.go:327 +0xa4a fp=0xc000072750 sp=0xc0000725f8 pc=0x45e02a
runtime.ensureSigM.func1()
        /home/canary/.encore/encore-go/src/runtime/signal_unix.go:1000 +0x115 fp=0xc0000727e0 sp=0xc000072750 pc=0x477435
runtime.goexit()
        /home/canary/.encore/encore-go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000727e8 sp=0xc0000727e0 pc=0x480121
created by runtime.ensureSigM
        /home/canary/.encore/encore-go/src/runtime/signal_unix.go:983 +0xbd

goroutine 34 [syscall]:
runtime.notetsleepg(0x0?, 0x0?)
        /home/canary/.encore/encore-go/src/runtime/lock_futex.go:236 +0x34 fp=0xc000212790 sp=0xc000212758 pc=0x419e74
os/signal.signal_recv()
        /home/canary/.encore/encore-go/src/runtime/sigqueue.go:152 +0x2f fp=0xc0002127b0 sp=0xc000212790 pc=0x47c82f
os/signal.loop()
        /home/canary/.encore/encore-go/src/os/signal/signal_unix.go:23 +0x1d fp=0xc0002127e0 sp=0xc0002127b0 pc=0xdbb61d
runtime.goexit()
        /home/canary/.encore/encore-go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0002127e8 sp=0xc0002127e0 pc=0x480121
created by os/signal.Notify.func1.1
        /home/canary/.encore/encore-go/src/os/signal/signal.go:151 +0x2e

goroutine 20 [select]:
runtime.gopark(0x126bce8, 0x0, 0x9, 0x18, 0x1)
        /home/canary/.encore/encore-go/src/runtime/proc.go:381 +0xfd fp=0xc00021cde8 sp=0xc00021cdb8 pc=0x44dc5d
runtime.selectgo(0xc00021cfb0, 0xc000072f80, 0x0?, 0x0, 0x0?, 0x1)
        /home/canary/.encore/encore-go/src/runtime/select.go:327 +0xa4a fp=0xc00021cf40 sp=0xc00021cde8 pc=0x45e02a
os/signal.NotifyContext.func1()
        /home/canary/.encore/encore-go/src/os/signal/signal.go:288 +0xa8 fp=0xc00021cfe0 sp=0xc00021cf40 pc=0xdbaf68
runtime.goexit()
        /home/canary/.encore/encore-go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00021cfe8 sp=0xc00021cfe0 pc=0x480121
created by os/signal.NotifyContext
        /home/canary/.encore/encore-go/src/os/signal/signal.go:287 +0x2d9

goroutine 21 [chan receive]:
runtime.gopark(0x126b920, 0xc000216058, 0xe, 0x17, 0x2)
        /home/canary/.encore/encore-go/src/runtime/proc.go:381 +0xfd fp=0xc0000736e0 sp=0xc0000736b0 pc=0x44dc5d
runtime.chanrecv(0xc000216000, 0x0, 0x1)
        /home/canary/.encore/encore-go/src/runtime/chan.go:583 +0x31e fp=0xc000073770 sp=0xc0000736e0 pc=0x413a7e
runtime.chanrecv1(0xc00015bec0?, 0x0?)
        /home/canary/.encore/encore-go/src/runtime/chan.go:442 +0x18 fp=0xc000073798 sp=0xc000073770 pc=0x4136f8
encore.dev/appruntime/shared/shutdown.(*Tracker).WatchForShutdownSignals.func1()
        /home/canary/.encore/runtime/appruntime/shared/shutdown/shutdown.go:46 +0x56 fp=0xc0000737e0 sp=0xc000073798 pc=0xdbc696
runtime.goexit()
        /home/canary/.encore/encore-go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000737e8 sp=0xc0000737e0 pc=0x480121
created by encore.dev/appruntime/shared/shutdown.(*Tracker).WatchForShutdownSignals
        /home/canary/.encore/runtime/appruntime/shared/shutdown/shutdown.go:45 +0x2dc

goroutine 23 [syscall]:
syscall.Syscall(0x0, 0x3, 0xc0001b9000, 0x1000)
        /home/canary/.encore/encore-go/src/syscall/syscall_linux.go:69 +0x57 fp=0xc000125668 sp=0xc0001255d8 pc=0x4a1ff7
syscall.read(0x3, {0xc0001b9000, 0x1000, 0x1000})
        /home/canary/.encore/encore-go/src/syscall/zsyscall_linux_amd64.go:711 +0xca fp=0xc000125708 sp=0xc000125668 pc=0x49fa0a
syscall.Read(0x3, {0xc0001b9000, 0x1000, 0x1000})
        /home/canary/.encore/encore-go/src/syscall/syscall_unix.go:178 +0x6c fp=0xc000125780 sp=0xc000125708 pc=0x49b9cc
internal/poll.ignoringEINTRIO(0x126bdb8, 0x3, {0xc0001b9000, 0x1000, 0x1000})
        /home/canary/.encore/encore-go/src/internal/poll/fd_unix.go:794 +0x98 fp=0xc000125820 sp=0xc000125780 pc=0x543298
internal/poll.(*FD).Read(0xc000136960, {0xc0001b9000, 0x1000, 0x1000})
        /home/canary/.encore/encore-go/src/internal/poll/fd_unix.go:163 +0x310 fp=0xc0001259a8 sp=0xc000125820 pc=0x53b070
os.(*File).read(0xc000134d60, {0xc0001b9000, 0x1000, 0x1000})
        /home/canary/.encore/encore-go/src/os/file_posix.go:31 +0x7e fp=0xc000125a30 sp=0xc0001259a8 pc=0x54d47e
os.(*File).Read(0xc000134d60, {0xc0001b9000, 0x1000, 0x1000})
        /home/canary/.encore/encore-go/src/os/file.go:118 +0xdd fp=0xc000125ad0 sp=0xc000125a30 pc=0x54ac1d
go:(*struct { io.Reader; io.WriteCloser }).Read(0xc00013b040, {0xc0001b9000, 0x1000, 0x1000})
        <autogenerated>:1 +0x89 fp=0xc000125b48 sp=0xc000125ad0 pc=0xf89c29
bufio.(*Reader).Read(0xc000136a20, {0xc000222000, 0xc, 0xc})
        /home/canary/.encore/encore-go/src/bufio/bufio.go:237 +0x37c fp=0xc000125c80 sp=0xc000125b48 pc=0x7e8dfc
io.ReadAtLeast({0x12b4f20, 0xc000136a20}, {0xc000222000, 0xc, 0xc}, 0xc)
        /home/canary/.encore/encore-go/src/io/io.go:332 +0x177 fp=0xc000125d20 sp=0xc000125c80 pc=0x52d9d7
io.ReadFull({0x12b4f20, 0xc000136a20}, {0xc000222000, 0xc, 0xc})
        /home/canary/.encore/encore-go/src/io/io.go:351 +0xa5 fp=0xc000125db0 sp=0xc000125d20 pc=0x52dbc5
github.com/hashicorp/yamux.(*Session).recvLoop(0xc0001c4180)
        /home/canary/go/pkg/mod/github.com/hashicorp/yamux@v0.1.1/session.go:536 +0x172 fp=0xc000125f88 sp=0xc000125db0 pc=0xf826f2
github.com/hashicorp/yamux.(*Session).recv(0xc0001c4180)
        /home/canary/go/pkg/mod/github.com/hashicorp/yamux@v0.1.1/session.go:515 +0x1e fp=0xc000125fc0 sp=0xc000125f88 pc=0xf8251e
github.com/hashicorp/yamux.newSession.func1()
        /home/canary/go/pkg/mod/github.com/hashicorp/yamux@v0.1.1/session.go:118 +0x2b fp=0xc000125fe0 sp=0xc000125fc0 pc=0xf7ec0b
runtime.goexit()
        /home/canary/.encore/encore-go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000125fe8 sp=0xc000125fe0 pc=0x480121
created by github.com/hashicorp/yamux.newSession
        /home/canary/go/pkg/mod/github.com/hashicorp/yamux@v0.1.1/session.go:118 +0x53b

goroutine 24 [select]:
runtime.gopark(0x126bce8, 0x0, 0x9, 0x18, 0x1)
        /home/canary/.encore/encore-go/src/runtime/proc.go:381 +0xfd fp=0xc000218b08 sp=0xc000218ad8 pc=0x44dc5d
runtime.selectgo(0xc000218f30, 0xc000218cb0, 0x0?, 0x0, 0x2?, 0x1)
        /home/canary/.encore/encore-go/src/runtime/select.go:327 +0xa4a fp=0xc000218c60 sp=0xc000218b08 pc=0x45e02a
github.com/hashicorp/yamux.(*Session).sendLoop(0xc0001c4180)
        /home/canary/go/pkg/mod/github.com/hashicorp/yamux@v0.1.1/session.go:467 +0x1b2 fp=0xc000218f88 sp=0xc000218c60 pc=0xf81cb2
github.com/hashicorp/yamux.(*Session).send(0xc0001c4180)
        /home/canary/go/pkg/mod/github.com/hashicorp/yamux@v0.1.1/session.go:456 +0x1e fp=0xc000218fc0 sp=0xc000218f88 pc=0xf81a9e
github.com/hashicorp/yamux.newSession.func2()
        /home/canary/go/pkg/mod/github.com/hashicorp/yamux@v0.1.1/session.go:119 +0x2b fp=0xc000218fe0 sp=0xc000218fc0 pc=0xf7ebab
runtime.goexit()
        /home/canary/.encore/encore-go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000218fe8 sp=0xc000218fe0 pc=0x480121
created by github.com/hashicorp/yamux.newSession
        /home/canary/go/pkg/mod/github.com/hashicorp/yamux@v0.1.1/session.go:119 +0x596

goroutine 25 [select]:
runtime.gopark(0x126bce8, 0x0, 0x9, 0x18, 0x1)
        /home/canary/.encore/encore-go/src/runtime/proc.go:381 +0xfd fp=0xc000088d38 sp=0xc000088d08 pc=0x44dc5d
runtime.selectgo(0xc000088f90, 0xc0000756e8, 0x0?, 0x0, 0x0?, 0x1)
        /home/canary/.encore/encore-go/src/runtime/select.go:327 +0xa4a fp=0xc000088e90 sp=0xc000088d38 pc=0x45e02a
github.com/hashicorp/yamux.(*Session).keepalive(0xc0001c4180)
        /home/canary/go/pkg/mod/github.com/hashicorp/yamux@v0.1.1/session.go:349 +0xd3 fp=0xc000088fc0 sp=0xc000088e90 pc=0xf80813
github.com/hashicorp/yamux.newSession.func3()
        /home/canary/go/pkg/mod/github.com/hashicorp/yamux@v0.1.1/session.go:121 +0x2b fp=0xc000088fe0 sp=0xc000088fc0 pc=0xf7eb4b
runtime.goexit()
        /home/canary/.encore/encore-go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000088fe8 sp=0xc000088fe0 pc=0x480121
created by github.com/hashicorp/yamux.newSession
        /home/canary/go/pkg/mod/github.com/hashicorp/yamux@v0.1.1/session.go:121 +0x605

goroutine 51 [select]:
runtime.gopark(0x126bce8, 0x0, 0x9, 0x18, 0x1)
        /home/canary/.encore/encore-go/src/runtime/proc.go:381 +0xfd fp=0xc000219b38 sp=0xc000219b08 pc=0x44dc5d
runtime.selectgo(0xc000219eb8, 0xc000219ce8, 0x0?, 0x0, 0x0?, 0x1)
        /home/canary/.encore/encore-go/src/runtime/select.go:327 +0xa4a fp=0xc000219c90 sp=0xc000219b38 pc=0x45e02a
github.com/hashicorp/yamux.(*Stream).Read(0xc000226000, {0xc00038e071, 0x1, 0x1})
        /home/canary/go/pkg/mod/github.com/hashicorp/yamux@v0.1.1/stream.go:145 +0x586 fp=0xc000219ee8 sp=0xc000219c90 pc=0xf85006
net/http.(*connReader).backgroundRead(0xc00038e060)
        /home/canary/.encore/encore-go/src/net/http/server.go:674 +0x98 fp=0xc000219fc0 sp=0xc000219ee8 pc=0x8b2778
net/http.(*connReader).startBackgroundRead.func2()
        /home/canary/.encore/encore-go/src/net/http/server.go:670 +0x2b fp=0xc000219fe0 sp=0xc000219fc0 pc=0x8b264b
runtime.goexit()
        /home/canary/.encore/encore-go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000219fe8 sp=0xc000219fe0 pc=0x480121
created by net/http.(*connReader).startBackgroundRead
        /home/canary/.encore/encore-go/src/net/http/server.go:670 +0x17c

**Comment by eandre** [comment]
Hi @peakstack, sorry for the delay in getting back to you here. This should work in the latest Encore release. Can you have a look and make sure it now works on your end as well? Thanks.

**Comment by peakstack** [comment]
Works now, thanks!
