### ISSUE TITLE
Returning custom error messages on auth handlers

### ISSUE THREAD

**Issue by Minivera** [encoredev/encore#75]
Hi,

I have a auth handler that looks something like this:

```go
//encore:authhandler
func AuthHandler(ctx context.Context, token string) (auth.UID, *UserData, error) {
	response, err := GetUserInternal(ctx, &GetUserInternalParams{
		token: token,
	})
	if err != nil || response == nil {
		log.WithError(err).Warning("Failed to authenticate user")
		return "", nil, nil
	}

	if response.User.Status == model.UserStatus_Pending {
		log.Warning("Authentication failed, user is still pending")
		return "", nil, nil
	}
	if response.User.Status == model.UserStatus_Denied {
		log.Warning("Authentication failed, user is denied")
		return "", nil, nil
	}

	return auth.UID(strconv.FormatInt(response.User.ID, 10)), &UserData{
		ID:       response.User.ID,
	}, nil
}
```

I would like to be able to return custom unauthenticated messages for each of the three returns I have so a user knows why their auth failed. If I omit the error and return an empty string, the error message is something like "auth token missing", which is not very actionable for my users. If I do return the error, the 401 error turns into a 500 error with my message shown.

I could mode this code to my endpoints instead, but it's a lot of duplicated code. I would like to be able to do something like returning a `&errs.Error` to customize the return code from an auth handler error.

**Comment by wisdommatt** [comment]
@eandre I will like to work on adding this to the documentation

**Comment by eandre** [comment]
Thank you @wisdommat, please do! Let me know if you want some help or guidance. Really appreciate the help!

**Comment by Minivera** [comment]
Apologies for closing the issue randomly, miss-click.

**Comment by wisdommatt** [comment]
@eandre i just made a pull request to add this to the docs
