### ISSUE TITLE
Parser error: prob recursion

### ISSUE THREAD

**Issue by acreditacion** [encoredev/encore#760]
╭─[Stack Trace]
├─▶ codegen.(*Generator).Overlays        /home/runner/work/encore/encore/encr.dev/v2/codegen/gen.go:86
├─▶ v2builder.BuilderImpl.Compile.func1  /home/runner/work/encore/encore/encr.dev/v2/v2builder/v2builder.go:156
├─▶ etrace.Sync2[...]                    /home/runner/work/encore/encore/encr.dev/internal/etrace/etrace.go:20
├─▶ v2builder.BuilderImpl.Compile        /home/runner/work/encore/encore/encr.dev/v2/v2builder/v2builder.go:115
├─▶ run.(*Run).buildAndStart.func1       /home/runner/work/encore/encore/encr.dev/cli/daemon/run/run.go:293
╰─▶ optracker.(*AsyncBuildJobs).Go.func1 /home/runner/work/encore/encore/encr.dev/internal/optracker/async.go:50

**Comment by eandre** [comment]
Hi @acreditacion, can you provide some more information? The complete error, as well as ideally a reproducer? Thank you!

**Comment by acreditacion** [comment]
Hi, here's the file with the complete log. I'll try to make a reproducible repo. [err.log](https://github.com/encoredev/encore/files/11736118/err.log)

With recursion I'm refering to [gorm-style]() struct fields. 

```go
type A struct {
    ID string
    // ...
    Bs []*B
}

type B struct {
    ID string
    // ...
    A *A
}
```

**Comment by acreditacion** [comment]
Also have a failed build id `11esjcsb0mgd1t3ssvjg` on project `prisma-api-owti`

**Comment by eandre** [comment]
Thanks @acreditacion, investigating.
