### ISSUE TITLE
Flow doesn't show databases for `sqldb.NewDatabase(...)`, only for `sqldb.Named(...)`

### ISSUE THREAD

**Issue by HectorMalot** [encoredev/encore#883]
Hi, 
I think I found a minor bug in the flow visualisation of databases. It shows the database icon on all services where I used `sqldb.Named(...)` to define the database (I think this was the original syntax before it became reference only) and doesn't show the database icon for services where the database is defined with `sqldb.NewDatabase(...)`. Was able to confirm this across multiple applications in both the local and cloud dashboard.

**Comment by eandre** [comment]
Thanks @HectorMalot, this should be resolved now!
