### ISSUE TITLE
Typescript generated client type error with slice optional query parameters

### ISSUE THREAD

**Issue by PhakornKiong** [encoredev/encore#924]
Generated a typescript client that have optional query parameters that is slice of string.

`encore gen client -e local -l typescript > ./client.ts`

```go
type queryParameters struct {
	Name []string `query:"id" encore:"optional"`
}

func World(ctx context.Context, query queryParameters) (*Response, error) {
	rlog.Debug("hello world", "query", query)
	msg := "Hello, " + "!"
	return &Response{Message: msg}, nil
}
```

result in

```typescript
export interface queryParameters {
        Name?: string[]
    }

const query = makeRecord<string, string | string[]>({
      id: params.Name.map((v) => v),
  })
```
and IDE is complaining that `params.Name` might be undefined.

Reproducible repo 
https://github.com/PhakornKiong/encore-ts-codegen/blob/master/client.ts

Probably can be fixed by optional chaining?
![image](https://github.com/encoredev/encore/assets/30017432/e4fa50c8-3f08-4d37-9530-8a7ab0a00d5b)

**Comment by Delta456** [comment]
I will be taking up to solve this issue.
