### ISSUE TITLE
Having no tests causes the build to fail.

### ISSUE THREAD

**Issue by MatthewJamesBoyle** [encoredev/encore#926]
**Issue**
builds fails if you do not have any test files.

**How to repro**
Consider an app with the following structure:
<img width="319" alt="image" src="https://github.com/encoredev/encore/assets/3738421/6ad51b97-07bf-4f39-b218-197ce02deb15">

when I deploy it, the build fails as there are no tests.
<img width="801" alt="image" src="https://github.com/encoredev/encore/assets/3738421/38ea3627-0586-4ecd-b13e-7b825508f7d5">

Adding an empty test file fixes it:
<img width="821" alt="image" src="https://github.com/encoredev/encore/assets/3738421/40ea60ae-37ee-4b41-98ae-57ae58f94c12">

**Expectation**
Whilst bad practise, there is situations where having no test files is fine. I think providing a warning log but the build succeeding would be a good outcome.

**Comment by eandre** [comment]
I believe real issue is not that there were no tests, but that there were no Go packages:

```
$ mkdir foo && cd foo && go mod init example.com

$ go test ./...
go: warning: "./..." matched no packages
no packages to test

$ echo $?
1
```

Whereas if you have a package:
```
$ echo "package foo" > foo.go

$ go test ./...
?   	example.com	[no test files]

$ echo $?
0
```

I'm not sure why Go made the distinction to treat "no matching packages" as a test failure; I guess to avoid mistakes. I believe if you have a matching Go package without tests Encore won't treat the tests as failing.

All that said, maybe Encore should treat this scenario as failing the build, and not just the tests? The "One or more tests failed" error is certainly confusing.

**Comment by MatthewJamesBoyle** [comment]
hmm I did have a go package though:
<img width="694" alt="image" src="https://github.com/encoredev/encore/assets/3738421/db1e8b0e-1cb6-45e9-83de-796bb324a33d">

**Comment by MatthewJamesBoyle** [comment]
Ok I reproed this.

- I ran encore create app
- I created a project called "testing-no-tests"
- I selected blank project.
- I created a package as follows:
<img width="988" alt="image" src="https://github.com/encoredev/encore/assets/3738421/2739ab53-c639-40a6-805a-cae1f658430b">

- I ran git push encore
- The deploy failed: https://app.encore.dev/testing-no-tests-tv9i/deploys/staging/147po86agipf5vipittg

**Comment by eandre** [comment]
But did you actually commit the `thing/thing.go` file? I believe the error you're seeing only happens when there are no Go packages.

**Comment by MatthewJamesBoyle** [comment]
Aha I'm not sure I did :) will close!
