### ISSUE TITLE
Proposal: Cron support

### ISSUE THREAD

**Issue by eandre** [encoredev/encore#95]
## Summary
We propose a simple mechanism for scheduling recurring tasks ("cron jobs").

## Motivation
Encore today provides great support for building APIs that execute some business logic in response to some external trigger (a user taking an action in a frontend, a webhook being called, and so on). But there's no built-in way to internally trigger something to happen. While there are many such use cases that we want to support natively, the simplest and most flexible is support for cron jobs.

## Design
Cron's original design is incredibly simple: specify when (or how frequently) a command should be executed. But when translated to building reliable systems, it turns out there are [many nuances](https://sre.google/sre-book/distributed-periodic-scheduling/):

* If execution fails, what failure mode is appropriate? Running the cron job more than once, or possibly not running it at all? (see [The Two Generals' Problem](https://en.wikipedia.org/wiki/Two_Generals%27_Problem))
* What to do about partial failures? What if a cron job performs two tasks, and one succeeds but the other fails?
* If a cron job is supposed to be launched every minute, and it takes more than a minute to complete, what should happen? Should two instances run concurrently? Should the second launch be skipped? Should the delay be measured from the stop time of the previous job, or from the start of it?

And so on. What seemed simple at the surface turned out to be quite complex. At the same time we'd like to get a solution out sooner rather than later, so it's important that the design choices are (1) reasonable defaults, and (2) forward-compatible to support different trade-offs above, over time.

To provide a portable implementation, we propose to start with a design that's based on the [Kubernetes CronJob](https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/) design. Specifically to make the following assumptions:

* Jobs are expected to be idempotent, meaning it's possible the same job is run more than once
* If a job is still running by the time the next job is supposed to start, another instance is started and both jobs run concurrently

### Configuration
In order to define cron jobs, we propose to extend the `encore.app` configuration file (which is in JSON format) with a new `cron` key:

```js
"cron": [
	{
		// Required keys:
		"endpoint": "service.Endpoint",
		"schedule": "*/1 * * * *", // or "@hourly" etc

		// Optional keys (with defaults):
		"timezone": "UTC", // time zone the schedule is based on
		"prod": true,      // whether to run in prod environments
		"dev": true,       // whether to run in dev environments
		"local": true,     // whether to run for local development
	},
	...
]
```

Encore will validates all of these at compile-time. The endpoint must be a `public` or `private` endpoint which takes no parameters; that is, the signature is `func Endpoint(context.Context) error` or `func Endpoint(context.Context) (*Response, error)`.

Cron configuration will be updated at deployment time. For local development with `encore run` changes will be reflected immediately (with live reload). For Kubernetes deployments the cron job will be configured as a Kubernetes CronJob object.

We believe this design strikes a good balance between supporting the most common use cases while being simple and portable. Adding support for additional use cases with different tradeoffs should be quite straightforward and backwards compatible by extending the configuration schema above.

**Comment by pbrazdil** [comment]
I agree with taking Kubernetes CronJob design approach, it looks straightforward and what I would expect without any supripses. I like the config approach as well.

I am not a fan of endpoints without params only limitation. Sometimes it would be very helpful to be able to have params available for use. If it's unreasonably time expensive to implement I will be able to live without it, no problem with that.

**Comment by eandre** [comment]
Thanks @pbrazdil for the feedback! What use cases do you imagine for passing parameters? Could you define a parameter-less endpoint for use with cron that calls another endpoint with parameters?

**Comment by vilhelmmelkstam** [comment]
What do you think about the posibility to run cron jobs for individual environments? We have a use case where we have an environment for demo purposes (a production environment) which we regularly want to add new data to. 

Is there otherwise any way to dynamically in the endpoint retreive what environment we are running in, e.g. via some environment variable? In that case we could guard when to run the code.

**Comment by eandre** [comment]
Adding that support would make the configuration much more complex. I think your idea of supporting querying the environment at runtime is a reasonable one and something we need for other use cases as well!

**Comment by Willyham** [comment]
Seems like a good pragmatic approach for the short/mid term to me. Long term, I think it would be nice to consider the possibility of a "task/job queue" approach to this, which might let us specify some of the retry semantics, and open up the possibility of a more powerful API for programatic tasks (e.g. I want to spawn some job every hour after somebody signs up in my app for the first 8 hours). We'd also then get sub-minute resolution (I'm currently building a system outside of encore which requires this).

There are some existing projects you could take inspiration from like. https://github.com/RichardKnop/machinery
