### ISSUE TITLE
Running tests shouldn't require Docker with no database

### ISSUE THREAD

**Issue by kblake** [encoredev/encore#98]
I newly installed encore and created a new default hello world application.
I went to run the tests via `encore test ./...` and the output says `pull docker image: exit status 1`.

I'm on MacOS running Go 1.15.6. 

Any reasons why I'm getting this vs a pass or fail message?

**Comment by kblake** [comment]
Nevermind. I had to have Docker running in order for the tests to run. So I'm good now.

**Comment by eandre** [comment]
Thanks so much @kblake for the feedback! You actually shouldn't need Docker for tests (unless your application uses a database, which is deployed in Docker for local development), so that's a bug since you used the Hello World example. Reopening and will fix, thank you!

**Comment by mateusnobre** [comment]
Hi Andre, can I take this one? I just found the bug following the documentation, from what I understood, we have to:
- Make sure the test passes on applications that don't use databases (specifically, the hello world example) without need to have docker installed or running

I'm trying to understand the CLI code and where exactly I have to change things (I'm new to open source), if you can guide me.

I was paying special attention to this [file](https://github.com/encoredev/encore/blob/4bb4ad775bab0ff93defdc9e0c0b24027b9a2f70/cli/daemon/run/tests.go), am I right looking in the right place?
