### ISSUE TITLE
Support optional params and enums in OpenAPI client generation

### ISSUE THREAD

**Issue by jakobskrym** [encoredev/encore#986]
Currently, the generation of OpenAPI clients does not parse whether or not a parameter is optional. As we are using this client to power our [docs](https://docs.skrym.com/), we now need to have workarounds if we want to specify that a parameter is optional. At the moment we are just looking if the description includes the word 'optional', but this is easy to forget.

Similarly, as we have quite a few external-facing endpoints that accept parameters that are effectively enums, it would be very helpful if we could provide a list of permitted values. 

I am happy to look into this myself if needed, but in that case I need help with being pointed in the right direction. Also not really sure how to set up Encore locally etc.

**Comment by jakobskrym** [comment]
Friendly ping on this @marcuskohlberg @eandre - and also happy new year! 🎉

**Comment by Akos-T** [comment]
Hi @jakobskrym , @marcuskohlberg , @eandre 

Is the issue with optional fields still relevant? I have the feeling PR #1028 solved the issue, but let me know.

How about the enums? I guess that's still open

**Comment by jakobskrym** [comment]
> Hi @jakobskrym , @marcuskohlberg , @eandre
> 
> Is the issue with optional fields still relevant? I have the feeling PR #1028 solved the issue, but let me know.
> 
> How about the enums? I guess that's still open

Looks like it, closing this! Thanks for looking out @Akos-T
